atlassian/atlascode

package-lock.json
package.json

- Fix create JIRA issue screen. 
- Bug: create JIRA page was blank. 
- Root Cause: A new i18n requirement from a version bump in atlaskit/panel
- Resolution: Roll back the version of the dependency 
- Drawback: exposes a vulnerability. 
- Drawback Mitigation: will fix forward. This is exposed in the last stable version, so we aren't regressing.

AXON-26 fix create JIRA issue

---

HOMEPAGE.md
README.md
package.json
src/lib/ipc/models/common.ts

- Searched over code for instances of "bitbucket.org/atlassian"
- Removed all relevant finds. Some finds were not removed because they are not impacted by the migration

[AXON-26] GH Migration: de-bitbucketing

---

.github/workflows/release-nightly.yaml
.github/workflows/release.yaml

Remove the `echo` we forgot in commands

[AXON-23] chore: remove echo

---

CHANGELOG.md

Adds Changelog in preparation for release

Version 3.2.0 Changelog Prep

---

src/react/atlascode/config/auth/CloudAuthButton.tsx
src/react/atlascode/onboarding/AltCloudAuthButton.tsx
src/react/atlascode/onboarding/OnboardingPage.tsx

- Changes some html ids from dot style to kebab style.

kebab id for some recent id changes 

---

scripts/release.sh

We haven't consistently updated the Changelog. Our customers are asking for this to be consistent. 
This will help enforce consistency.

Issue 94: enforce changelog updates on release

---

CHANGELOG.md

changelog 3.4.5

---

src/util/featureFlags/client.ts

merged in var before new linting. need to remove

remove var in fg client

---

src/atlclients/clientManager.ts
src/jira/jira-client/providers.ts

Users were reporting issues authenticating with PAT on BitBucket DC. 
This fixes it. 
I looked into adding unit tests for this file. There are many things to mock out here to make this efficient. 
I'm punting on unit tests here.
Instead, I will look at UI testing.
|--------|--------|
| ![Screenshot 2025-02-14 at 4 04 22 PM](https://github.com/user-attachments/assets/ca3b9cdb-4a06-482f-a4dd-43b81bf10229) | ![image](https://github.com/user-attachments/assets/ee4cb61e-05be-4a72-9e80-fbc21ad1d398) |

[AXON-110] BitBucket DC PAT Auth Bug

---

src/analytics.ts
src/atlclients/loginManager.ts
src/lib/webview/controller/onboarding/onboardingWebviewController.ts
src/vscAnalyticsApi.ts
src/webview/onboarding/vscOnboardingActionApi.ts

What:
* Added `isOnboarding` field to `atlascode authenticated` event
* fixed login action flow
Why:
* to distinguish onboarding authentication events to measure experiment success

[AXON-130] experiment auth UI flow analytics

---

src/atlclients/responseHandlers/JiraPKCEResponseHandler.ts

Remove a bit of logic that doesn't go anywhere
It kind of wasn't, I am ashamed to admit 🙇

[AXON-46] chore: clean up a bit of unused code

---

src/react/atlascode/common/form/useFormValidation.tsx

Reverts unneeded changes from https://github.com/atlassian/atlascode/pull/140/files 
After doing so, things work. 
Bug Repro: https://github.com/atlassian/atlascode/issues/77#issuecomment-2680505924 
Slack thread for more context: https://atlassian.slack.com/archives/C07TU1NSUCE/p1740461390410209

Fix bug in 3.4.8 - Revert some change from PR 140

---

dataportal.yaml
src/analytics.ts

Reverts atlassian/atlascode#142

Revert "Update analytics file doc"

---

.github/PULL_REQUEST_TEMPLATE.md

A consistent hurdle for author is testing for DC on Bitbutcket changes. 
This should help address this.

add instruction for BB changes

---

src/views/jira/treeViews/customJqlViewProvider.test.ts
src/views/jira/treeViews/customJqlViewProvider.ts
src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.test.ts
src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.ts

In the Sidebar UI experiment, when adding a new site, the JQL query for it wasn't being initialized.
This is because the handler that is taking care of this is residing in `jiraContext.ts` which is not  initialized in the experiment.
Added the implementation in `CustomJQLViewProvider`.
Basic checks:
Advanced checks:

[AXON-238] Fixed missing JQL initialization in Sidebar UI experiment

---

src/react/atlascode/pullrequest/PullRequestDetailsPage.tsx

This PR contains no functional changes. This only aims to break the monolithic `PullRequestDetailsPage` into smaller components within the same file —
1. **PullRequestHeader**: Handles the top app bar with title and action buttons
2. **PullRequestTitleSection**: Handles the title editor and branch information
3. **PullRequestMainContent**: Contains all the main panels (summary, issues, commits, etc.)
4. **PullRequestSidebar**: Contains the right sidebar with author, reviewers, and date information
Improves readability and review ability of future changes to this page.
The effective code remains the same — however I've done a round of sanity and the CI tests should cover it more extensively.

PullRequestDetailsPage: Refactored main function to be more modular

---

CODEOWNERS

- Dev Inner Loop team has asked for the ability to have fast reviews in their timezone due to the rate of work they are contributing. 
- Axon team is aligned to this, provided that: 
1. Quality of PRs stays high. PRs should have clear problem statements and loom video reviews of the user experience. Testing on both Cloud and Data Center should be done, as relevant.
2. The Axon team maintains control over the release process. 
3. The Axon team reserves the right to revert any PR for any reason, or no reason. Including this PR. 
4. Recommendation: Dev Inner Loop team to look at metrics on a regular (weekly?) basis to confirm metrics look okay. https://app.amplitude.com/analytics/atlassian/chart/nuq7zdi1

CODE OWNERS for dev inner loop team

---

src/commands.ts
src/commands/bitbucket/pullRequest.ts
src/container.ts

This PR adds a command which allows us to programmatically open a pull request in Atlascode.

feat: add PR open command

---

CHANGELOG.md
src/webviews/components/issue/view-issue-screen/JiraIssuePage.tsx

- Issue #308 reported an issue around some Jiras not loading because some fields aren't present and we didn't handle this correctly. 
- Manual testing via making a project on a my personal jira site that didn't have one of the key fields. 
Basic checks:

Fix Issue #308 - Some Jira Issues Cannot load - Make sure we are only rendering fields that exist

---

src/webviews/components/issue/view-issue-screen/sidebar/IssueSidebarCollapsible.tsx

Fix overflow bug introduced in this PR: https://github.com/atlassian/atlascode/pull/307
Loom demo DC/Cloud: https://www.loom.com/share/0dd074a948684f9a912499bc5bbc3002?sid=50c41685-5245-4f9b-8dc0-ec3572f03f70
Basic checks:

AXON-327: fix overflow bug

---

src/webviews/components/issue/create-issue-screen/CreateIssuePage.tsx

add bottom margin to create issue page for better accessibility
before: 
after: 
manual testing
Basic checks:

Add bottom margin to create issue page

---

package.json
src/atlclients/authInfo.ts
src/config/configuration.ts
src/config/model.ts
src/constants.ts

Simply removing unused stuff from config and configuration-related code.

First pass at cleaning up unused config

---

CHANGELOG.md
src/webviews/components/App.css
src/webviews/components/fieldValidators.ts
src/webviews/components/issue/AbstractIssueEditorPage.tsx
src/webviews/components/issue/common/JiraIssueTextArea.tsx
src/webviews/components/issue/create-issue-screen/CreateIssuePage.tsx

Raised by this issue: https://github.com/atlassian/atlascode/issues/355
Adding a required number field crashed create issue page
- was due to faulty field validation
manual testing
Basic checks:

[AXON-356] Fix: Adding required story point field causing create issue page to crash

---

src/extension.ts

roll back breaking change for plyglot folk
tested ployglots after revert
Basic checks:

AXON-358: roll back globa window stuff

---

.github/workflows/release-nightly.yaml
.github/workflows/release.yaml

chore: temporarily disable OpenVSX publishing in release.yaml

---

src/analytics.ts

Added some logic to replace `site ids`, `ip addresses`, and `host names` from the error messages sent to telemetry.
Basic checks:

Sanitize error messages for telemetry

---

src/views/jira/treeViews/customJqlViewProvider.test.ts
src/views/jira/treeViews/customJqlViewProvider.ts
src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.test.ts
src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.ts
src/views/jira/treeViews/utils.test.ts

Not much to say here 😃 
Basic checks:

Added more Jira TreeView UTs

---

src/react/atlascode/startwork/StartWorkPage.tsx
src/util/files.test.ts
src/util/files.ts
src/util/reactpromise.test.ts
src/util/reactpromise.ts
src/util/shell.test.ts
src/util/shell.ts
src/webviews/components/WebviewComponent.tsx
testsutil/fileReaderMock.ts
testsutil/index.ts

Self explanatory 😄 
Check comments for some extra details.

Added more util UTs

---

CHANGELOG.md

Updated changelog and fixed the 'Report an issue' link

Updated changelog for 3.6.6

---

CHANGELOG.md
src/analytics.ts
src/views/notifications/badgeDelegate.test.ts
src/views/notifications/badgeDelegate.ts

Some basic analytics events for badge notificaiton changes.
Manual test. 

AXON-403: Analytics for notifications

---

.eslintrc.js
e2e/tsconfig.e2e.json
src/lib/.eslintrc.js
src/react/.eslintrc.js

Small prep PR to reformat several config files that seemingly slipped through the cracks of our linter
It wasn't, really ;)
Basic checks:

[AXON-385] chore: reformat code

---

resources/schemas/pipelines-schema.json

Quick update to the pipeline schema, based on #447
Clicked around a bunch :)
Basic checks:

[AXON-440] Pipeline schema update

---

src/views/notifications/atlassianNotificationNotifier.ts

solve for unseen counts being clipped at 20

---

.vscode/launch.json.example
webpack.extension.dev.js
webpack.extension.prod.js
webpack.react.dev.js
webpack.react.prod.js

Thanks @sdzh-atlassian for this PR!
This PR changes the `launch.json.example` file to show how to use the .env file during debug time.
It also cleans up an unused env replacement in webpack.

Use .env file when debugging

---

CHANGELOG.md
src/atlclients/authStore.test.ts
src/atlclients/authStore.ts
src/atlclients/clientManager.test.ts
src/atlclients/clientManager.ts
src/atlclients/loginManager.test.ts
src/container.ts

AXON-448-notification-errors-refresh

---

.vscodeignore
resources/rovo-dev/script.sh
src/resources.ts
src/rovo-dev/rovoDevProcessManager.ts

A set of more verbose errors for when rovodev fails to start ;)
Manually! ;D
Basic checks:

Chore: slightly more verbose error messages

---

e2e/helpers.ts
e2e/tests/playwright.spec.ts

Login badge check
[video.webm](https://github.com/user-attachments/assets/fb5e7fca-dfbc-4b91-ab9d-5f864a6760c5)
Logout badge check
[video.webm](https://github.com/user-attachments/assets/bfbd4c13-d185-45d9-8ade-ac3de7223033)

[AXON-450] When I am logged out of jira, I have a badge notification asking for authentication for Jira

---

src/react/atlascode/rovo-dev/common.tsx

Rovo Dev: Accept -> Keep

---

src/extension.ts
src/rovo-dev/rovoDevApiClient.test.ts
src/rovo-dev/rovoDevApiClient.ts
src/rovo-dev/rovoDevWebviewProvider.ts

This change introduces a check to ensure that the Rovo Dev version satisfies the minimum version requirement for Atlascode.

[AXON-588] Rovo Dev min-version supported for chat

---

e2e/helpers/update-jira-issue.ts
e2e/tests/jira/updateLabelsFlow.spec.ts
e2e/wiremock-mappings/mockedteams/BTS-1/suggestlabels.json
e2e/wiremock-mappings/mockedteams/BTS-1/updatelabels.json

[video.webm](https://github.com/user-attachments/assets/ba0149b0-68fd-4ef8-ac32-9721dce584de)
Basic checks:

AXON-593: E2E Labels field

---

e2e/tests/jira/renameIssue.spec.ts

AXON-614: fix rename issue e2e test failing locally

---

src/react/atlascode/rovo-dev/RovoDev.css
src/react/atlascode/rovo-dev/rovoDevViewStyles.tsx

[AXON-634][Rovo Dev] Center chat in wide window size

---

src/react/atlascode/rovo-dev/rovoDevView.tsx

[AXON-671][Rovo Dev] Fix the chat auto-scrolling that sometimes it doesn't scroll through the end

---

package-lock.json

1 critical severity vulnerability in package `form-data`

[AXON-674] Fixed 1 critical severity vulnerability in package `form-data`

---

CHANGELOG.md
src/react/atlascode/common/form/helpers.test.tsx
src/react/atlascode/common/form/helpers.tsx
src/react/atlascode/common/form/useFormValidation.tsx
src/react/atlascode/common/types.tsx
src/react/atlascode/config/auth/dialog/AuthDialog.tsx
src/react/atlascode/config/auth/dialog/CustomSiteAuthForm.tsx
src/react/atlascode/constants.ts
src/react/atlascode/util/authFormUtils.test.ts
src/react/atlascode/util/authFormUtils.ts

This change fixes #560 .
Fix issue when the save button is enabled without valid credentials in the authentication dialog. And issue when the save button is disabled if there is an error in one of the tabs ( reason - the error state was not cleared when switching the tabs or from type, e.g from Jira Server to Jira Cloud ). 
**Changes that were made:**
- extracted existed constants, types and  helpers in AuthDialog to separate files
- add fields and errors clearing between tab switch and form type switch ( Jira Server -> Jira Cloud )
- add approproate fields and errors validation ( depending on tab or form type )
- add tests for existed and added helpers
**Steps to reproduce first issue:**
- Go to "Atlassian Settings"
- Click "Other options"
- Enter the `https://jiracloud.domain.com` as …

AXON-591: fix save button is enabled without valid credentials

---

src/analytics.test.ts
src/analytics.ts
src/react/atlascode/rovo-dev/rovoDevView.tsx
src/react/atlascode/rovo-dev/rovoDevViewMessages.tsx
src/rovo-dev/rovoDevWebviewProvider.ts

Fires 'Files changed summary shown' telemetry event.

[AXON-717][Rovo Dev] Fire 'Files changed summary shown' telemetry event

---

src/analytics.test.ts
src/analytics.ts
src/react/atlascode/rovo-dev/messaging/ChatStream.tsx
src/react/atlascode/rovo-dev/rovoDevView.tsx
src/react/atlascode/rovo-dev/rovoDevViewMessages.tsx
src/rovo-dev/rovoDevWebviewProvider.ts

Fires 'Git push' telemetry event.

[AXON-719][Rovo Dev] Fire 'Git push' telemetry event

---

package.json
src/commands.ts
src/constants.ts
src/react/atlascode/rovo-dev/promptContext/promptContextCollection.tsx
src/react/atlascode/rovo-dev/rovoDevView.tsx
src/rovo-dev/rovoDevDecorator.ts
src/rovo-dev/rovoDevWebviewProvider.ts

Adding a new command to send selection to rovodev context
Basic checks:

Axon 522 send to context

---

src/rovo-dev/rovoDevCodeActionProvider.ts

Tiny PR to also enable sending context from the code action menu

[AXON-522] Add code action to send context

---

src/react/atlascode/rovo-dev/RovoDev.css
src/react/atlascode/rovo-dev/messaging/ChatMessageItem.tsx
src/react/atlascode/rovo-dev/messaging/ChatStream.tsx
src/react/atlascode/rovo-dev/messaging/MessageDrawer.test.tsx
src/react/atlascode/rovo-dev/messaging/MessageDrawer.tsx
src/react/atlascode/rovo-dev/rovoDevView.tsx
src/react/atlascode/rovo-dev/tools/ToolCallItem.tsx

Added general loading state for rovo dev chat when the response is generating, or executing plan.
Demo:
https://www.loom.com/share/24061e39023444ff9043b39bd520035a
manual testing
Basic checks:

[AXON-530] Added general loading state

---

src/react/atlascode/rovo-dev/rovoDevView.tsx
src/rovo-dev/rovoDevWebviewProvider.ts

- Allows for a new session to reset the chat entirely (files & PR buttons & deep plan) 
Manually

AXON-732: Fix bug for new session to fully reset

---

src/analytics.test.ts
src/rovo-dev/performanceLogger.test.ts

Fixed UT failures introduced in #648

Fixed UT failures introduced in #648

---

src/react/atlascode/rovo-dev/RovoDev.css
src/react/atlascode/rovo-dev/prompt-box/promptContext/promptContextCollection.tsx
src/react/atlascode/rovo-dev/prompt-box/promptContext/promptContextItem.tsx
src/react/atlascode/rovo-dev/rovoDevView.tsx

|----|-----|
| <img width="366" height="130" alt="image" src="https://github.com/user-attachments/assets/e46db583-3fe0-4fe3-893d-b4463a9b8598" /> | <img width="368" height="137" alt="image" src="https://github.com/user-attachments/assets/a51a29a0-9823-4dca-8ab0-4d6667ce1b68" /> |

[AXON-780] Fix Rovo Dev promptbox textarea margin

---

e2e/tests/bitbucket/repositoryConnection.spec.ts

Temporary skip flaky e2e test

---

src/react/atlascode/rovo-dev/RovoDev.css
src/react/atlascode/rovo-dev/rovoDevView.tsx

- Adds a disclaimer text to the bottom of the rovo dev chat. 
- Matches requirements from design & legal 
- Just a text change 
Manual

AXON-498 Uses ai disclaimer

---

resources/rovo-dev/script.sh
src/rovo-dev/rovoDevProcessManager.ts
src/siteManager.ts

- BBY User ID var 
- ApplicationID for Rovo Dev IDE tracking 
- Version updates for script and proces manager

Rovo Dev distinguishing var for analytics, BBY userid for analytics, update to script versions

---

src/rovo-dev/rovoDevProcessManager.ts

Update applicationId for Rovo Dev

change the name of appId

---

package.json
src/constants.ts
src/container.ts

[AXON-493] Add command to open .agent.md in editor

---

src/container.ts
src/rovo-dev/rovoDevProcessManager.ts
src/siteManager.ts

@sdzh-atlassian you know what this is

Rovo Dev: prefer hello site to check for Rovo Dev availability

---

package.json

- Before: Names & Categories were not set correctly 
- After: Each command is associated to Jira, Bitbucket, or Rovo Dev if releated. Else Atlassian
https://www.loom.com/share/a1a04310e978432ba41c2c6260a75094?sid=737054c7-d29c-4a95-9959-5120976020ac
Manual + E2E 
Basic checks:

Update Command Pallete Categories & Names

---

src/rovo-dev/rovoDevApiClient.test.ts
src/rovo-dev/rovoDevApiClient.ts
src/rovo-dev/rovoDevWebviewProvider.ts

This change syncs the Chat Session ID with Rovo Dev for telemetry correlation.
Basic checks:

[AXON-906][Rovo Dev] Sync Chat Session ID with Rovo Dev

---

playwright.config.js

AXON-909: Enabled 3 retries for flaky e2e tests

---

package-lock.json
package.json

`"@atlaskit/datetime-picker": "^15.13.1" -> "^17.0.13"`
Basic checks:

AXON-842: Upgrade datetime to 17.0.13

---

e2e/page-objects/fragments/PullRequestsNavigation.ts
e2e/scenarios/bitbucket/connectRepository.spec.ts
playwright.config.js

AXON-876: Flaky connectRepo e2e test

---

__mocks__/packagejson.ts
jest.config.ts
package.json
src/rovo-dev/rovoDevProcessManager.ts

Rovo Dev version config in package.json

---

package.json

Upgrade Rovo dev min version to `0.11.13` to get command functionality
manually
Basic checks:

upgrade rovo dev min version to 0.11.13

---

src/jira/fetchIssue.test.ts
src/jira/fetchIssue.ts
src/jira/issuesForJql.test.ts
src/jira/issuesForJql.ts
src/webviews/createIssueWebview.ts
src/webviews/jiraIssueWebview.ts

Performance Experiment is over and removed old code. Now all of our users will receive the Jira performance improvements!
Basic checks:

Cleaned up Jira performance experiment: AXON-963 :)

---

scripts/version/get-latest-nightly.sh
scripts/version/get-next-nightly.sh

Cleanup from the build debugging session :)
It was not (FeelsBadMan)

chore: clean up verbose output in build scripts

---

CHANGELOG.md

Backfill CHANGELOG.md for the perf improvements

---

src/commands.ts

- Login bug for new auth onboard
- Manual Testing
Basic checks:

Fix for Jira login commands

---

src/react/atlascode/rovo-dev/messaging/ChatStream.tsx

[AXON-996] Fix missing Pull Request button in BBY

---

src/analytics.test.ts
src/analytics.ts
src/analyticsTypes.ts
src/vscAnalyticsApi.test.ts
src/webview/common/vscCommonMessageActionHandler.test.ts

- If a user is logged into a site as @atlassian.com" email address associated with @atlassian.com, then there should be a flag to distinguish this. 
Manual, with break points

Track Internal atlassian users

---

src/rovo-dev/rovoDevProcessManager.ts

As requested by the Rovo Dev CLI team.
It hasn't.

[AXON-1032] Updating Rovo Dev xid to rovodev-ide-vscode

---

src/rovo-dev/rovoDevWebviewProvider.ts

Regression introduced in #917 .

Fix broken replay after webview provider refactoring

---

src/rovo-dev/rovoDevProcessManager.ts
src/rovo-dev/rovoDevWebviewProvider.ts

Added a bunch of missing `await`, and process management error handling, to better help diagnose issues when initializing Rovo Dev.

[Rovo Dev] Added a bunch of missing await, and process error handling

---

src/react/atlascode/rovo-dev/rovoDevLanding.tsx

Align with https://www.figma.com/design/icNW3QwXXHJZciWjp0OrPh/Atlascode--RovoDev-?node-id=1227-143991&m=dev 
Manual

Update Rovo Dev API Token Button 

---

src/rovo-dev/rovoDevWebviewProvider.ts

[Rovo Dev] Fix Login landing page not showing up after logging out from API token

---

CHANGELOG.md
src/siteManager.test.ts
src/siteManager.ts

Fix of the error that we get when connecting several cloud sites via api token. The issue was in credentialId generation. For each site connected with api token credentialId generation is based on site host and userId, but we've rewrited it in `addSites` function and that was the reason of getting the error.
**Current behaviour**: 
**Fixed behaviour** ( connecting each site separately without getting any error and deleting it separately as well)
**Loom with current and fixed behaviour:**
https://www.loom.com/share/fe7e061ad0224b8082a110483be3b3c1
Basic checks:

AXON-1099: fix error while connecting cloud sites with api token

---

CODEOWNERS

Add @Blastoplex and @mattcolman to `CODEOWNERS`
N/A

chore: add BBY folks to CODEOWNERS

---

CHANGELOG.md
src/react/atlascode/config/auth/dialog/AuthDialog.tsx

Fixed issue when pressing 'Enter' to submit the form doesn't work
Basic checks:

AXON-1210: add enter handling to submit the form

---

src/container.ts

Rachit was experiencing an issue in cursor where the rovo dev ff was resolving to false. I believe this will fix his issue. 
Manually

Bug fix: Move logic to @atlassian.com in the other place too for Rovo Dev (no longer using Rovo Dev FF)

---

src/rovo-dev/rovoDevProcessManager.ts

Unquote Rovo Dev site url argument

---

src/react/atlascode/rovo-dev/rovoDevView.tsx
src/rovo-dev/rovoDevChatProvider.ts
src/rovo-dev/rovoDevWebviewProvider.ts
src/rovo-dev/rovoDevWebviewProviderMessages.ts

Merged the communication for several type of messages into one, to prepare a future change where messages can be sent in bulk (== replay optimization).

Simplify Rovo Dev messaging to webview

---

package-lock.json
src/atlclients/issueBuilder.ts

|---|---|
| <img width="553" height="152" alt="image" src="https://github.com/user-attachments/assets/d8f7685d-fbb9-461b-83c9-318540b125af" /> | <img width="565" height="154" alt="image" src="https://github.com/user-attachments/assets/1130e7f7-af4e-4f52-92a1-462b22bc9944" /> |
See image above :)
Basic checks:

fix: make issue suggestion errors more verbose

---

src/react/atlascode/rovo-dev/RovoDev.css
src/react/atlascode/rovo-dev/common/DialogMessage.tsx

[AXON-1298] Fix tool calls overflowing the Rovo Dev chat

---

src/rovo-dev/rovoDevWebviewProvider.ts

When the Rovo Dev panel gets dragged from one bar to another, its webview gets destroyed and recreated.
This is causing lots of issue today, which this change is not fixing.
This change only prevents the webview provider to re-initialize the process and consequently throw an error.

[AXON-1295] Fix error when dragging the Rovo Dev panel somewhere else

---

package-lock.json

https://github.com/advisories/GHSA-vj76-c3g6-qr5v

Fix vulnerability CVE-2025-59343

---

src/react/atlascode/rovo-dev/landing-page/RovoDevSuggestions.tsx
src/rovo-dev/rovoDevJiraItemsProvider.ts
src/rovo-dev/rovoDevWebviewProvider.ts
src/rovo-dev/rovoDevWebviewProviderMessages.ts

1. The Jira work items header should disappear when there are no items to display
2. The Jira work items section should refresh when the Rovo Dev Jira site changes

[AXON-1296] Fix Jira work items header and refreshing logic

---

package-lock.json
src/webviews/components/issue/view-issue-screen/mainpanel/IssueCommentComponent.test.tsx
src/webviews/components/issue/view-issue-screen/mainpanel/IssueCommentComponentAKE.test.tsx
src/webviews/components/issue/view-issue-screen/mainpanel/IssueMainPanel.test.tsx
src/webviews/components/issue/view-issue-screen/mainpanel/IssueMainPanelAKE.test.tsx

AXON-1302: Added Unit tests

---

README.md

Remove Closed Beta from readme

AXON-1343 Remove the word "closed" from beta descriptors
