atlassian/atlascode

- .github/workflows/build.yaml
- .github/workflows/release-nightly.yaml
- .github/workflows/release.yaml
When doing the round of bug bashing today, we caught that the `atlascode` feature flag client initialization vars are not getting passed to the build environment correctly.
Now they are 😉 
This is related to CI - so I've only run a pipeline to make sure things work, and checked that the environment variables propagate to the build env correctly. Once this is merged, I'll check the next `nightly` for any feature flag initialization issues
> [AXON-19] fix: pass FX3 client vars to build

- resources/schemas/README.md
- resources/schemas/pipelines-schema.json
- src/pipelines/pipelines-schema.test.ts
This is the change to update the schema for `bitbucket-pipelines.yaml` to what seems to be its latest publicly available version, straight from Bitbucket folks :) 
Sources:
* https://community.atlassian.com/t5/Bitbucket-questions/Scheme-URL-of-bitbucket-pipelines-yml/qaq-p/834807
* https://api.bitbucket.org/schemas/pipelines-configuration
```
npm run lint # OK
npm run test # OK
npm run extension:install # clicked around, made sure the pipeline files are validated properly
```
An example with a random new property
|--------|--------|
| ![image](https://github.com/user-attachments/assets/767183cb-088c-4d1e-ad2c-9671c319e0e0) | ![image](https://github.com/user-attachments/assets/766f86a9-f9f3-4f62-9909-01d592a2d115) |
> [AXON-23] fix: update the bitbucket-pipelines schema

- .github/workflows/release-nightly.yaml
- .github/workflows/release.yaml
Here we add the actual logic to push the pre-release builds of the extension, marked with `--pre-release`, to the VSCode Marketplace and OpenVSX repos
This is a CI change, so technically it wasn't, except for:
* Several previous nightly build runs
* Publish code being carried over from `release` path where it worked historically
> [AXON-23] Add pre-release logic to CI

- .github/workflows/release-nightly.yaml
- package.json
- Adds the pre-release flag on the nightly packaging command. 
- Done because of this error: 
```
Error: Cannot use '--pre-release' flag with a package that was not packaged as pre-release. Please package it using the '--pre-release' flag and publish again.
Error: Process completed with exit code 1.
```
Source: https://github.com/atlassian/atlascode/actions/runs/12242743894/job/34150733698
> AXON-23 prerelease flag on the packaging for nightly

- .github/workflows/release-nightly.yaml
Due to this error: 
```
! [remote rejected]   v3.1.1 -> v3.1.1 (push declined due to repository rule violations)
```
Source: https://github.com/atlassian/atlascode/actions/runs/12243113285/job/34151929479
> AXON-23 add '-nightly' to the GH tags to get around the tag restrictions

- .vscodeignore
I've noticed that our extension artifact has become quite bloated - and the problem became 1000 times worse once I've tried creating a local cache for e2e tests :D
This should hopefully curtail the bloat ;)
| | Latest nightly (3.1.7) | After the fix |
|-|-|-|
| Size | 3.77 MB | 1.7 MB |
| Composition | ![image](https://github.com/user-attachments/assets/9c203fd7-34d0-4e90-b7ae-689711470145) | ![image](https://github.com/user-attachments/assets/677d1ade-1ff5-43ad-beb6-39ed556c3d2f) |
* _Not thoroughly_ - but I've installed the version and poked around a bunch to make sure that icons still work, and components don't look weird
> [AXON-37] (PR-1) Fix .vscodeignore to not bloat the extension artifact

- .vscodeignore
Small chore - prevent __mocks__ folder from being rolled into `.vsix` artifact
| Before (latest [build](https://github.com/atlassian/atlascode/actions/runs/12360487221/job/34495554628)) | After (`npm run extension:package` |
|-|-|
| ![image](https://github.com/user-attachments/assets/e50b4bba-c438-4b66-9c61-291ca05f384d) | ![image](https://github.com/user-attachments/assets/8b8d45ec-194d-4dbb-8d6e-4ff9541b65c8) |
> [AXON-37] chore: add __mocks__ to vscodeignore

- src/react/atlascode/common/editor/MarkdownEditor.tsx
- src/react/atlascode/common/form/useFormValidation.tsx
- src/react/atlascode/config/auth/AuthDialog.tsx
- src/react/atlascode/pipelines/PipelineSummaryPage.tsx
- src/react/atlascode/pullrequest/InlineRenderedTextEditor.tsx
- src/webviews/components/RenderedContent.tsx
Edit: on second thought, __don't fix what's not broken__. I've tried making sure it all works - and quickly realized that I _really_ don't want to touch the old react code - at least not until we have reliable E2E tests. For now, I've just silenced the warnings instead. Hopefully eventually we rebuild the whole components where they appear
~My friend Copilot and I have just gone over the (very annoying) linter warnings :)~
~Unfortunately, I know basically nothing about the actual pages these bits of code renders - so some extra testing might be in order, especially for some of the fixes here 😢~
`npm run lint` - linter warnings no longer show up :)
> [AXON-38] chore: silence old linter warnings from React

- .vscodeignore
- src/atlclients/clientManager.ts
- src/atlclients/loginManager.ts
- src/react/atlascode/config/auth/AuthDialog.tsx
* VSCODE-1050: PAT auth for hosted BitBucket(like for hosted Jira)
Like the API of Jira and Bitbucket, the API of Bitbucket supports Bearer Auth using PAT instead of Basic Auth:
https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html
A number of other customers have expressed a need for this feature, not just us (Cloud Software Group): We disallow the use of HTTP Basic Auth for security reasons for the Confluence, Jira and Bitbucket APIs of our self-hosted services. Instead, we require the use of Bearer Auth using a PAT by the users.
A background information for this is that, that your security policy requires 2FA or alternatively tokens, password authentication without a 2nd factor as implemented in HTTP Basic Authentication is prohibited by company …
> Address comments in #28

- src/webviews/components/issue/JiraIssuePage.tsx
A temporary workaround to put into `nightly` so that we can hopefully dig a little deeper into #46 
With this, if we try to render markup for an `undefined` field - we  skip rendering that field, and we get an error message:
Some considerations on this:
* I might be missing something in the implementation - but this is super weird. The only field rendered on `JiraIssuePage` which could fail with that exact step should be `Summary` - but that feels _impossible_?
* By no means is this a long-term solution
* We _really_ need proper error handling in our pages :( Might be a good early task for @cabella-dot? 😉
* Randomly spotted a bunch of copy-pasted code and moved it to a loop
* Rendered the page with some fields hardcoded to `undefined as any`, saw the error message and the page without the …
> [AXON-40] fix: add slightly more graceful failures in JiraIssuePage

- resources/schemas/pipelines-schema.json
Pipelines team is going to support different arch in the near future, and this is the PR to add the new `arch` attribute to cloud runtime
> CICD-6783: Add arch attribute for cloud runtime in pipelines-schema.json

- .github/workflows/build.yaml
- .github/workflows/release-nightly.yaml
- .github/workflows/release.yaml
- e2e/scripts/in-docker
- e2e/tests/auth.test.ts
- e2e/tests/no-auth.test.ts
- package.json
- src/atlclients/authInfo.ts
- src/commands.ts
- src/container.ts
- src/react/atlascode/config/auth/AuthDialog.tsx
- src/webview/config/vscConfigActionApi.ts
- webpack.extension.dev.js
- webpack.extension.prod.js
- webpack.mui.webview.js
- webpack.react.dev.js
- webpack.react.prod.js
- webpack.react.webview.js
- Logins a test user using API Token. API token is set via environment variables. Check Repo secrets
- For community members, if needed, please use CI builds to run these tests.
> AXON-32 - Auth Test framework - Auth we go! (works only on local, no CI) 

- e2e/README.md
Small PR sort of unrelated to AXON-41 - I've noiticed that apparently `e2e/README.md` would get formatted every time `npm run format` is invoked
This PR is what `npm run format` does to the file :)
N/A
> [AXON-41] chore: format the repo (e2e/README.md)

- CHANGELOG.md
- src/atlclients/clientManager.ts
A long overdue fix for a very annoying problem.
Before, when several JIRA instances shared a credential, client from one of them would be reused for everything, leading to incorrect results. Now, we properly create clients for each JIRA instance independently
|--|--|
| ![image](https://github.com/user-attachments/assets/d1ecbb72-de86-49ba-858a-dd5041a3c8cb) | ![image](https://github.com/user-attachments/assets/5a587683-f12a-4c72-8512-2b0225141e3a) |
By doing a before and after 😉
> [AXON-42] fix: show correct JIRA issues under "My X issues"

- .github/workflows/release-nightly.yaml
- .github/workflows/release.yaml
Small PR to fix these warnings that appear in our builds:
Apparently the official github action for releases is no longer maintained, so this makes the repo use the highest-rated proposed alternative - [softprops/action-gh-release](https://github.com/softprops/action-gh-release)
It's almost a drop-in replacement, with an added benefit of combining the upload of artifacts into one action
Test release from this branch using the new action
Also, made sure that the build fails if the uploaded artifact isn't found:
> [AXON-43] chore: fix CI warnings about release actions

- src/analytics.ts
- src/analyticsTypes.ts
- src/lib/analyticsApi.ts
- src/lib/ipc/fromUI/common.ts
- src/lib/webview/controller/bbIssue/bitbucketIssueWebviewController.ts
- src/lib/webview/controller/bbIssue/createBitbucketIssueWebviewController.ts
- src/lib/webview/controller/config/configWebviewController.ts
- src/lib/webview/controller/onboarding/onboardingWebviewController.ts
- src/lib/webview/controller/pullrequest/createPullRequestWebviewController.ts
- src/lib/webview/controller/pullrequest/pullRequestDetailsWebviewController.ts
- src/lib/webview/controller/startwork/startWorkWebviewController.ts
- src/lib/webview/controller/welcome/welcomeWebviewController.ts
- src/react/atlascode/common/ErrorBoundary.tsx
- src/react/atlascode/config/ConfigPage.tsx
- src/react/atlascode/config/configController.ts
- src/vscAnalyticsApi.ts
- src/webview/common/vscCommonMessageActionHandler.ts
This is the 1st PR in a series related to improving our observability when something goes wrong.
In React, there's a concept of an [Error Boundary](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary) - a special component which is intended to address rendering errors in the tree, and which is very notably missing in our pages 😉
Further, we are already pulling [@atlaskit/analytics-next](https://atlaskit.atlassian.com/packages/analytics/analytics-next) as a dependency, which conveniently offers an [implementation](https://atlaskit.atlassian.com/packages/analytics/analytics-next/docs/error-boundary) we could use.
After the changes in this PR, we can receive an event with some data on rendering errors occuring in prod:
> ⚠️ Note: The exact structure …
> [AXON-41] Implement AtlascodeErrorBoundary

- src/analyticsTypes.ts
- src/react/atlascode/bbissue/BitbucketIssuePage.tsx
- src/react/atlascode/bbissue/CreateBitbucketIssuePage.tsx
- src/react/atlascode/config/ConfigPage.tsx
- src/react/atlascode/onboarding/OnboardingPage.tsx
- src/react/atlascode/pipelines/PipelineSummaryPage.tsx
- src/react/atlascode/pipelines/pipelineSummaryController.ts
- src/react/atlascode/pullrequest/CreatePullRequestPage.tsx
- src/react/atlascode/pullrequest/PullRequestDetailsPage.tsx
- src/react/atlascode/startwork/StartWorkPage.tsx
- src/react/atlascode/welcome/Welcome.tsx
`AtlascodeErrorBoundary` is now added to all pages of the newer architecture
* Built the extension, poked around, induced and observed some failures
> [AXON-41] Add error boundary to all pages except JIRA

- src/analyticsTypes.ts
- src/react/atlascode/pipelines/pipelineSummaryController.ts
- src/webviews/abstractWebview.ts
- src/webviews/components/issue/CreateIssuePage.tsx
- src/webviews/components/issue/JiraIssuePage.tsx
- src/webviews/components/issue/StartWorkPage.tsx
- webpack.extension.dev.js
- webpack.extension.prod.js
- webpack.mui.webview.js
- webpack.react.dev.js
- webpack.react.prod.js
- webpack.react.webview.js
This PR adds `AtlascodeErrorBoundary` to the remaining 3 pages, implemented with the older architecture and IPC.
Built the extension, ran things in debug, made sure analytics events are emitted
> [AXON-41] Add error boundary to JIRA pages

- src/analyticsTypes.ts
- src/react/atlascode/common/ErrorBoundary.tsx
Small follow-up from the previous AXON-41 PRs:
* Limit for the number of characters in the shortened stack: `150` -> `1500`
* Renamed the values of the enum for page names that show up in analytics events
Also - introduced some nomenclature for the different "legacy" page implementations, lol :D
Whatever new thing we build will be `v3` in these terms 😉 
Only the basic build tests, didn't do any special testing since this is a small change
> [AXON-41] chore: fix stack limit and webview name strings

- e2e/tests/auth.test.ts
- e2e/tests/no-auth.test.ts
- src/atlclients/authInfo.ts
- src/constants.ts
- src/container.ts
- src/react/atlascode/config/auth/AuthDialog.tsx
Our prior implementation of e2e testing relied on jira-dev.com
This was a flawed starting point, because jira-dev.com is only accessible while on the Atlassian VPN, which this GitHub repo is not. 
Idea: Use a site that is still free to use, but not protected by a VPN. 
Solution: Make a site in the free-tier of JIRA usage on atlassian.net 
Name: axontest2025.atlassian.net 
- Make an exception for handling this so we aren't forced to use OAuth. 
How was this tested? 
- I test the VPN issue with jira-dev.com by trying to visit it on a personal device without VPN access. Resulted in a 403 
- I tested this locally to confirm the e2e test can run while on VPN 
- I am raising this PR to test if the GitHub actions pipeline will allow this to work. (May the odds be ever in my favor)
> [AXON-32] allow for testing e2e in non-VPN environments

- CHANGELOG.md
- package-lock.json
- package.json
- src/webviews/components/ErrorBanner.tsx
- src/webviews/components/issue/AbstractIssueEditorPage.tsx
Small rabbit hole started from chasing an easy win 🐰 
We got a user report that editing the `Reporter` field on the JIRA issue page causes the whole page to crash. 
This PR fixes the error banner used there - which was very ungracefully failing to render.
This PR ALSO addresses the root cause of the error that needed the banner in the first place - by temporarily replacing the `/rest/api/2/user/recommend` API with `/rest/api/2/user/search` for that field
https://github.com/user-attachments/assets/19ec081a-a2b3-4492-9582-1ce18a9e58de
https://github.com/user-attachments/assets/e50391ac-0dd6-4ef7-b129-3df568efb0a4
https://github.com/user-attachments/assets/95d4fd61-fd24-423b-bf2e-99ec38e32ded
Rather painfully 😢
Built the extension, used a project where editing `Reporter` is allowed, edited …
> [AXON-49] fix: prevent JIRA page crash on Reporter edit

- .vscode/launch.json.example
- package-lock.json
- package.json
- webpack.extension.dev.js
Small devprod improvement - added another launch configuration that would leverage `webpack --watch`, at least to some extent. The wall clock time of iterating in UI went from ~35 sec per build to instant
With this approach, if you run `npm run dev` in an shell somewhere, VSCode extension host starts without prerequisites, and uses whatever files are generated by `webpack` on the fly.
I've tried doing something fancier with hotswap, launch configurations, and webpack dev server - but unfortunately this is the only configuration which worked reliably enough
Pretty extensively? Iterated the UI a bunch with the new launch configuration, and some alternatives that didn't make it into this PR :D
> [AXON-45] chore: speed up iteration on UI with --watch (devprod)

- package.json
Project IDX looks for extensions that are compatible with the engine that it is running on. If the extension claims it runs on a higher version, it won't show up to be installed. 
To fix this, we are lowering our compatiblity requirement to match what we are actually compatible with. 
Note: we could go lower, we just haven't tested if we can. 1.77.0 is from March 2023
> Revert to vscode engine compatibility >=1.77.0

- src/atlclients/loginManager.ts
Video of solution working: 
https://github.com/user-attachments/assets/0b8bab9e-8136-45a0-9e95-f14b1cfedacf
Issue: https://github.com/atlassian/atlascode/issues/77
Community pointing out the issue: https://github.com/atlassian/atlascode/pull/41/files 
Solution: 
1. Unfortunately, unlike before the credential object didn't contain the username. That why in the past PR, the `/rest/api/latest/build/capabilities` API was introduced to get the username info 
2. The header returns this in URI encoding eg: bwieger%40atlassian.com 
3. So that needs to be convert to standard text eg: bwieger@atlassian.com
4. And then the special characters can be replaced with the prior regex.
> AXON-111 revert changes that made special chars not work for BB DC

- package.json
- scripts/githooks/pre-commit
This PR contains a pre-commit hook that runs `lint` before every commit.
The script is installed in the local .git configuration via `npm install`.
> Add pre-commit hook, installed at npm i

- src/util/html.test.ts
- src/util/html.ts
- src/webviews/components/issue/AbstractIssueEditorPage.tsx
- src/webviews/components/issue/CommentComponent.tsx
- src/webviews/components/issue/CreateIssuePage.tsx
- src/webviews/components/issue/JiraIssuePage.tsx
To render descriptions and comments of Jira tickets, we use a "rendered html" field returned by the server.
When we request the jira ticket information, Jira DC responds with a rendered html that contains images referenced with an absolute URL, which work fine.
Jira Cloud instead responds with a rendered html that contains images referenced with a relative URL, which cannot be resolved because the `<base>` url is set to some vscode react stuff.
The fix is to pre-process the "rendered html" before displaying it, fixing the relative URLs to absolute.
Tested:
- Jira Cloud, image in description and comments
- Jira DC, image in description and comments
Before:
After:
> [Axon 97] Fix image rendering in Jira Cloud tickets' description and comments

- src/bitbucket/bitbucket-cloud/pullRequests.ts
- src/bitbucket/bitbucket-server/pullRequests.ts
- src/bitbucket/model.ts
Many of the bitbucket APIs that we used around tasks are now deprecated in favor of the "comments" APIs. 
Using the "tasks" API on version of BitBucket DC 8.0 and later result in 404s. 
Since we don't have a clear pattern for fetching the version of the backend we are attaching to, the solution here uses a try catch pattern looking for 404s. 
I chose to prioritize the new APIs because I !assume! that most of our future (and perhaps current) users are on 8.0 and later. 
8.0 was release around May 2022 (3 years old) 
**[BEFORE](https://www.loom.com/share/de22e2c02842496ea52b057e27e4b0f6)**
**[AFTER](https://www.loom.com/share/171712ebfeeb47c195160efb5a3f4d49?sid=278594d6-e6e6-4d3a-8100-96646b9165cf)**
> AXON-113: Fix Bitbucket DC 8.0 and later bugs with 404s 

- package-lock.json
- package.json
- src/atlclients/strategy.test.ts
- src/atlclients/strategy.ts
- src/atlclients/strategyCrypto.ts
When working on the other auth stuff, I've come to the point of doing a pretty big change around `strategy.ts`
To minimize the risk of breaking thing, I'm first creating a bunch of unit tests for the existing logic with minimal changes.
The original plan was to literally touch nothing and only add tests, however there are some small necessary changes:
* encryption-related stuff is moved out of `strategy.ts` to a separate file `strategyCrypto.ts` - primarily because it caused issues with `jest` for some reason
* created trivial functions for verifier and basic auth
* bumped `@types/jest` version and added `@jest/globals` to resolve the weird `it.each` issue
Despite lots of logic, these things are effectively data classes, so I'm only testing the happy path to make sure the output doesn't …
> [AXON-46] chore: add unit tests for auth strategies

- CHANGELOG.md
- src/react/atlascode/config/auth/SiteAuthenticator.tsx
- src/util/featureFlags/features.ts
- tsconfig.json
Jira Cloud Auth with API tokens is fully supported. Removing the feature flag that gates this. 
Feature flag was rolled to 100% and soaked for >7 days
> AXON-114 : remove feature flag for RDE Auth 

- CHANGELOG.md
- src/webviews/components/issue/CreateIssuePage.tsx
- src/webviews/createIssueWebview.ts
The issue repros when the first server is an unreachable server, like a shut down Jira DC.
The page was stuck, and looping on a circle of error/refresh, because of a wrong condition on the react page.
The fix is in `CreateIssuePage.tsx`, the rest of the changes are minor random improvements.
> [AXON-117] Fix 'Create issue webview' stuck on the loader

- CHANGELOG.md
- src/react/atlascode/startwork/startWorkController.ts
- src/webview/singleViewFactory.ts
Couple of code bugs were preventing the existing tab to refresh correctly.
| Bug | Fixed |
|-----|-----| 
| ![axon-134-bug](https://github.com/user-attachments/assets/247466c8-cddf-46b6-9992-11f0bc36bbd2) | ![axon-134-fixed](https://github.com/user-attachments/assets/393f4895-28b5-4e3f-9815-01ec187e24d6) |
> [AXON-134] Fix for 'Start work' not working when another 'Start work' tab is open

- src/atlclients/authInfo.ts
- src/atlclients/loginManager.ts
- src/atlclients/oauthDancer.ts
- src/atlclients/strategy.test.ts
- src/atlclients/strategy.ts
- src/atlclients/strategyData.ts
- src/lib/ipc/fromUI/config.ts
- src/lib/webview/controller/config/configWebviewController.ts
- src/react/atlascode/config/auth/SiteAuthenticator.tsx
- src/react/atlascode/config/configController.ts
- src/uriHandler/actions/simpleCallback.ts
- src/uriHandler/atlascodeUriHandler.ts
The next PR in the chain to enable a smooth 3LO-from-anywhere experience in the extension ;)
With this, we can now use an external service to bounce authentication from - in this PR it's referred to as the `JiraRemote` OAuth strategy
Short recap of the changes:
* Fork the existing monolithic OAuth process, split it in 2 parts (start via user action / finish via deeplink)
* Add a button (completely invisible to everyone, FF pending) to trigger the new oauth
* Add an ability to configure OAuth client from the environment on the fly, for dev purposes
* Move OAuth strategy data into their own file, now with a bunch of docs
* Implement URIHandler path for `/auth`
* A whooooole lot of IPC/messaging boilerplate 😞 
What's notably missing:
* OAuth attempt/session management
* The way to trigger …
> [AXON-46] Add remote auth flow using atlascode-backend

- src/react/atlascode/startwork/StartWorkPage.tsx
From: https://bitbucket.org/atlassianlabs/atlascode/issues/771/error-start-work-failed-because-of-a-space
If the branch name contains a space, or ends with a space, the branch can't be created.
The cleanest way to solve this is adding a field validation on the UI itself, so it doesn't allow the space character to be typed. To be consistent with other logic, the space character is being replaced with a dash `-` while typing.
Typing "This is a branch" will result in typing "This-is-a-branch".
> [AXON-145] Added branch name validation for space characters

- CHANGELOG.md
- src/analytics.test.ts
- src/analytics.ts
- src/ipc/issueActions.ts
- src/lib/analyticsApi.ts
- src/lib/ipc/fromUI/startWork.ts
- src/lib/webview/controller/startwork/startWorkActionApi.ts
- src/lib/webview/controller/startwork/startWorkWebviewController.ts
- src/react/atlascode/startwork/StartWorkPage.tsx
- src/react/atlascode/startwork/startWorkController.ts
- src/vscAnalyticsApi.ts
- src/webview/startwork/vscStartWorkActionApi.ts
- src/webviews/components/issue/StartWorkPage.tsx
- src/webviews/startWorkOnBitbucketIssueWebview.ts
- src/webviews/startWorkOnIssueWebview.ts
With this PR, the Start Work view exposes a toggle switch to control if the new branch should be automatically pushed to remote or not.
The toggle switch is defaulted to `true`, to keep parity with today's behavior.
The status of the new toggle is being instrumented within the `workStarted` event.
This addresses the following open issues:
[Add settings to not push instantly to remote](https://github.com/atlassian/atlascode/issues/90) #90
[Create branch as a local branch during "Start work"](https://bitbucket.org/atlassianlabs/atlascode/issues/538/create-branch-as-a-local-branch-during)
Here how it looks like:
> [AXON-109] Expose toggle switch to push branch to remote (Start work)

- src/react/atlascode/common/pmf/PMFDialog.tsx
New: ![image](https://github.com/user-attachments/assets/23dc9b46-7faa-4529-a95f-ff145eb579e7)
Per https://atlassian.slack.com/archives/C07TU1NSUCE/p1739847651381139
> pmf repharsing

- src/atlclients/authInfo.ts
- src/atlclients/authStore.ts
- src/siteManager.ts
This PR addresses the weird behaviour that happens whenever we try to delete one site from several sharing a credential:
|-|-|
| ![sites-before](https://github.com/user-attachments/assets/21aae4fc-98e4-4b43-aa08-29081450c64f) |  ![sites-after](https://github.com/user-attachments/assets/460fac1e-fe5a-4534-8431-5cecb8b2ba93) |
After the change, it's possible to remove the sites individually. However, while working on this, I've found a couple other rather frustrating issues which will require a more comprehensive rework 😢
Specifically:
* An error banner still seems to randomly appear at the top when deleting sites too fast due to a race condition
* JQL configuration persists in the settings even after the credentials for the site have been removed. That might be intended, …
> [AXON-17] Fix weird site list behaviour

- src/container.ts
- src/extension.ts
- src/lib/ipc/toUI/common.ts
- src/react/atlascode/onboarding/OnboardingPage.tsx
- src/util/featureFlags/client.ts
- src/util/featureFlags/features.ts
- src/webview/singleViewFactory.ts
What: 
* added support for Statsig experiment values to be sent to FE for experimentation
* set up AA experiment implementation in Onboarding flow
Demo loom: 
https://www.loom.com/share/7888dc16753649fc9d6cc16e6e36f2da
> Axon 144 experiment auth UI flow statsig set up

- package.json
Context - currently, we have a pretty strict syntax that requires `TODO:` for the `Create JIRA Issue` annotation to pop up:
Update to the default keywords for ticket creation, per suggestion in Slack:
* Removed trailing `:`
* Added a bunch of extra options
Please note that this is just the default values. The docs aren't very clear - but I'm pretty sure this wouldn't affect users who already made changes to these settings
It was edited right in GH UI, so it kind of wasn't :) TBD in next nightly or manual build
> [AXON-161] Update default issue creation keywords

- src/util/featureFlags/features.ts
* Added AA exp value to FeatureFlagClient init
> AXON-192: add AA exp code to features init

- src/react/atlascode/config/auth/SiteAuthenticator.tsx
- src/react/atlascode/config/auth/dialog/AuthDialog.tsx
> ⚠️ Note: found some issues while submitting the PR - hence draft
>   * ~~url parsing might be borked after rebase, somehow~~ - tested, works now
>   * ~~would be good to disable the `save` button in BB cloud~~ - maybe in a follow-up
> * Please note that this specifically DOESN'T address BB cloud auth, and targets BasicAuth/PAT on BB DC/server instead
This PR enables the custom auth flow for Bitbucket in RDE, in the same way as JIRA - except using BB [app password](https://support.atlassian.com/bitbucket-cloud/docs/app-passwords/) turned out to be a _really_ poor substitute for JIRA API token, so that's not available ;)
The rationale here is to enable folks who use BB Server/DC to authenticate remotely from RDEs via PAT/basic auth
| | Old | New |
|-|-|-|
| Local<br/> (no change) | …
> [AXON-149] (WIP) re-enable auth UI for bitbucket in RDE

- src/util/featureFlags/client.test.ts
- src/util/featureFlags/client.ts
- src/util/featureFlags/features.ts
The code was throwing exceptions because when failing to retrieve the data from the server (e.g., missing `.env` file), the fields `FeatureFlagClient._featureGates` and `FeatureFlagClient._experimentValues` were left uninitialized.
> Fix exceptions due to failures in FeatureFlagClient initialization

- src/atlclients/authInfo.ts
- src/atlclients/authStore.ts
- src/siteManager.ts
This is a PR where we revert the change in how site information is stored (credential ID vs credential ID+extra info). See [original PR](https://github.com/atlassian/atlascode/pull/79) for a before-and-after
We suspect this change might have been causing friction in the auth experience. The exact root cause is pending confirmation, but we've decided to roll this back anyway to err on the side of caution moving forward
Compiled the extension, did a couple rounds of authentication, poked around with JIRA functionality
> Revert "[AXON-17] (WIP) fix weird site list behaviour"

- src/react/atlascode/pullrequest/PullRequestDetailsPage.tsx
- src/react/atlascode/pullrequest/pullRequestDetailsController.ts
**Customer Problem**
The 'Checkout source Branch' button in the Pull Request view doesn't have a loading state, and it gives the impression that nothing is happening, and suddenly, it changes to 'Source branch Checkout out.'  
This PR will add a loading state to the 'Checkout source Branch' button, which will help to ensure that the checkout is in progress instead of clicking the button multiple times.
Loom Video: https://www.loom.com/share/c58dda9fb5bd494f979cbd940a955f6a?sid=43894cfe-7c32-4438-ad13-cbabec5ec227
> Loading state for "Checkout Source Branch" button

- src/container.ts
- src/extension.ts
- src/react/atlascode/onboarding/OnboardingPage.tsx
- src/util/featureFlags/client.test.ts
- src/util/featureFlags/client.ts
- src/util/featureFlags/features.ts
Loom: https://www.loom.com/share/19e0e4b8bfc347d58404b0bb4c75cfa3
Due to the nature of this experiment (only first time installers will be put into cohorts):
* changed experiment fetching to be outside of initialization
* implemented exp flow in `extension.ts` 
Now, only users whose `previousVersion === undefined` will be placed into exp cohorts:
* A - control
* B - jump to settings page auth
* C - jump to legacy auth flow
* D - jump to new auth flow
> Axon 201 implement experiment flow split

- src/react/atlascode/pullrequest/PullRequestDetailsPage.tsx
- src/react/atlascode/pullrequest/SummaryPanel.tsx
I have added a loading icon to the summary section which used to load the contents without any visual indication to the user. Now while the initial summary is loading the loading icon would be visible to the user.
> Add loading icon to summary panel

- .github/PULL_REQUEST_TEMPLATE.md
A fairly barebones template for pull request messages, outlining the guidance for what to include in the description, featuring:
* The stuff we outlined as often missing
* My own very subjective preferences
* Help from mr. copilot
The guidance text itself is largely hidden, if unchanged the PR message would render to this:
I'll test it and amend if necessary if there's any issues after this is in `main`
> [AXON-198] add pull request template

- package.json
- src/commands.ts
- src/util/featureFlags/client.ts
- src/views/jira/treeViews/constants.ts
- src/views/jira/treeViews/customJqlViewProvider.test.ts
- src/views/nodes/issueNode.test.ts
- src/views/nodes/issueNode.ts
To follow new designs for the sidebar tree view, this PR:
* adds `statusCategory` (to do, in prog, done) tags onto the side of each IssueNode on hover
* when new tag is clicked => open issue
* added testing for issueNode
Loom: 
https://www.loom.com/share/721aeda9fef64617a99a476289f5f1e0?sid=e4b1450f-bfe9-4c98-9b47-b8fdc30790e2
Added UT for IssueNode in `issueNode.test.ts`
Basic checks:
> AXON-189: adding status commands + new issueNode testing + put behind fg

- src/jira/transitionIssue.ts
When transitioning an issue's status, the new customJQL sidebar view would not automatically refresh. In this PR, I added the fix to this issue
Loom: https://www.loom.com/share/e558849edea248f7b908fc46f80f1ac7?sid=9d1345b4-8e04-447b-93ef-40745d20d245
Test + demo in loom
Basic checks:
> AXON-206: fix explorer not refreshing on issue status transition

- package.json
- src/commands/jira/assignIssue.ts
- src/jira/jqlManager.ts
- src/views/jira/treeViews/constants.ts
- src/views/jira/treeViews/customJqlViewProvider.test.ts
- src/views/jira/treeViews/customJqlViewProvider.ts
- src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.test.ts
- src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.ts
- src/views/jira/treeViews/utils.ts
- src/views/nodes/issueNode.test.ts
- src/views/nodes/issueNode.ts
This change refactors the implementation of the Custom JQL panel, removing its dependency from the classes `BaseTreeDataProvider` and `AbstractBaseNode`.
It also speeds up the rendering of the panel, returning the JQL nodes immediately and fetching their items in background.
It also fixes:
- the 'Assign to me' context menu in the Custom JQL panel
- showing only the customized JQLs, and not all of them
- jira issue status indicator in "Assigned Jira issues" view items
> Align the implementation of the new sidebar UI views

- jest.config.js
- package.json
- src/commandContext.ts
- src/commands.ts
- src/views/jira/treeViews/customJqlViewProvider.test.ts
- src/views/jira/treeViews/customJqlViewProvider.ts
- src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.test.ts
- src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.ts
- src/views/jira/treeViews/utils.test.ts
- src/views/jira/treeViews/utils.ts
- src/webviews/jiraIssueWebview.ts
* Made `customJqlTreeView` to only be visible when user has custom JQLs enabled
* Made `assignedToMeTreeView `and `customJqlTreeview` only visible when Jira Explorer is enabled
* fixed bug where assigning yourself in Issue view does not refresh the tree
* Add util tests for new JiraIssueNode for coverage on statusCategory tag assignment
* added relevant commands to AssignedToMeView
Loom:
https://www.loom.com/share/7b1f04900c164c08a83e2d7dd8ac85d7?sid=1546e877-1257-4ac0-a3f2-4a0c29ad4e8d
Unit testing + Manual testing
Basic checks:
> AXON-193: make customJqlTreeView only visible when user has custom JQLs + fix bug + add util tests

- package.json
- src/views/jira/treeViews/customJqlViewProvider.ts
Fix bug where custom jql view does not hide when unauthenitcating jia
loom: https://www.loom.com/share/d23c6526bbfa46bf811efe4bbee98efa?sid=203472a6-90e4-40ac-9f1c-59fd6138bcea
UT + manual test
Basic checks:
> no-issue: fix bug where custom jql view does not disappear when jira unauth

- src/views/nodes/commitSectionNode.ts
- src/views/pullrequest/pullRequestNode.ts
https://www.loom.com/share/4dc7f309eb42458383b5f42e32384dbb
TLDR -> I am trying to load PR data asynchronously. This way whatever data is needed is loaded first and other non-critical data is loaded later and treeItem is then refreshed.
I have tested this by running the debug mode and verifying that this opens up for larger repos. Also you can see in the loom video the test runs
Basic checks:
- [✅  ] `npm run lint` 
- [ ✅ ] `npm run test`
> Improving performance of large repo PRs by dividing APIs into critical and non-critical flows

- src/jira/fetchIssue.ts
- src/views/jira/searchJiraHelper.test.ts
- src/views/jira/searchJiraHelper.ts
This PR fixes this link that is broken when the new SidebarUI experiment is turned on
The root cause was the undefined JiraExplorer object being used to find the issue from the cache.
JiraExplorer is undefined because it represents the old jira issues view, which is turned off when the new views are enabled.
The fix is simply null-checking JiraExplorer before invoking it.
Additionally, I've wired up the SearchJiraHelper to use it as a cache.
Tested:
> [AXON-220] Fixed broken link after creating new issue within new SidebarUI experiment

- src/views/pullrequest/prCommentController.ts
Fixes #212 #24 
And BB Issue https://bitbucket.org/atlassianlabs/atlascode/issues/762/pr-comments-are-changed-to-object-object
Test on DC and Cloud 
See Loom: https://www.loom.com/share/3bd6debe9230489f91d3c27f1a3cec20
Basic checks:
**BEFORE (when editing a comment on a PR):** 
**AFTER**
> AXON-133: Comment on BB PR now work. Issue 212, 24 and BB Issue 762

- src/jira/jqlManager.ts
- src/views/jira/treeViews/customJqlViewProvider.test.ts
- src/views/jira/treeViews/customJqlViewProvider.ts
- src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.test.ts
- src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.ts
- src/views/jira/treeViews/utils.test.ts
- src/views/jira/treeViews/utils.ts
The bug is the following error when configuring two distinct custom JQL queries that return the same Jira issue:
The reason for this error is because we build the TreeItem id as `{issueKey}_{siteId}`, which is the same for the same issue across different JQL queries.
The solution is building the TreeItem id as `{issueKey}_{siteId}_{jqlEntryId}`.
To accomodate this solution, some other changes are required:
- in jqlManager, the jqlEntry for retrieving the default jql queries for the assigned jira work items needs to have a stable id, so depending for the reason it's generated (site initialization vs retrieve default queries) the id is generated differently
- a new TreeViewIssue interface is introduced to extend the fields of a MinimalIssue, and carry the jql source for it
Basic checks: …
> [AXON-239] Fix TreeItem id to allow same issue to appear twice

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- Changelog for https://github.com/atlassian/atlascode/pull/214
- PR Template update to remind PR Authors about the change log 
- No tests needed 
Basic checks:
Advanced checks:
> Changelog for bug fix, change to PR template to remind PR authors about changelog

- src/analytics.ts
- src/container.ts
- src/util/featureFlags/client.ts
- src/util/featureFlags/features.ts
This change is adding the `gateExposureBool` telemetry event to track the exposure of feature flags and experiments with boolean parameters.
The purpose of this new telemetry event is for debugging only, to verify that the stat-sig library is correctly evaluating feature flags and experiments, and the outcome of the check is what we expect.
Also, added the failure reason in telemetry for when initialization fails.
The new telemetry event will be reverted once the debugging is complete.
Basic checks:
Advanced checks:
> Add feature gates and experiment exposure telemetry events

- src/analytics.ts
- src/container.ts
- src/util/featureFlags/client.ts
- src/util/featureFlags/features.ts
Passing `"N/A"` as default value for a boolean experiment's parameter makes the function to fail.
Switched to a string parameter where the possible values are "Control" and "Test", and using a different value "Default" as the default value to distinguish them.
> Fixed debug telemetry for AA experiment

- CHANGELOG.md
- src/extension.ts
- src/jira/jqlManager.ts
- Users are reporting issues with commands not being registers. This appears to be due to poor error handling. #219 
- Although we haven't pinpointed were the errors are coming from, we have improved the error handling allow users to manually reset themselves by deleting all of their auths in the Settings > Jira > Authentication section and then re-authenticating 
- Manually tested with a user who was experiencing this. Unfortunately, we didn't grab the log before hand to understand the cause of the error. But the solution worked. 
Basic checks:
> better error handling

- src/container.ts
- src/util/featureFlags/features.ts
This changes removes the existing `Jira issues` sidebar panel, and it ships the two new sidebar panels `Assigned Jira work items` and `Custom JQL filters`:
| ![image](https://github.com/user-attachments/assets/722cd348-153d-4418-9ac3-e695c4b6ee8c) | ![image](https://github.com/user-attachments/assets/40437593-dbfd-4e32-925d-31e7b7d3bf92) |
|---|---|
The first panel shows all and only the issues assigned to the authenticated user, in a flat (non-hierarchical) view.
The second panel only shows the customized JQLs, and behaves similarly to the old `Jira issues` panel.
The second panel stays hidden if there aren't any customized JQL.
A new feature flag `atlascode-old-sidebar-treeview` has been introduced to quickly return to the old view in case of emergency.
Basic checks:
Advanced checks: …
> [AXON-247] Ship the new sidebar UI panels

- CHANGELOG.md
- src/views/jira/treeViews/utils.ts
This fixes `Error viewing custom query` #260 .
This is a regression introduced in https://github.com/atlassian/atlascode/pull/252
as this bug was already fixed in https://github.com/atlassian/atlascode/pull/217
Basic checks:
> Fix JQL registration issue in custom JQL panel

- .npmrc
- .vscodeignore
- src/atlclients/loginManager.test.ts
- src/util/featureFlags/client.test.ts
- src/views/jira/searchJiraHelper.test.ts
- src/views/jira/treeViews/customJqlViewProvider.test.ts
- src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.test.ts
- src/views/jira/treeViews/utils.test.ts
- testsutil/index.ts
- testsutil/miscFunctions.ts
Created a root folder `testsutil` where we can implement UT utility functions.
For now, we only have `forceCastTo<>`.
More to come 😄
> Refactor common test utilities into their folder

- src/jira/jqlManager.test.ts
- src/jira/jqlManager.ts
- src/views/jira/treeViews/utils.test.ts
- src/views/jira/treeViews/utils.ts
- testsutil/index.ts
- testsutil/miscFunctions.ts
Added UTs for the `jqlManager` and `util` related to JQLEntry creation and their ids.
Basic checks:
> Added tests related to the TreeView ID and JQL logic

- CHANGELOG.md
- src/react/atlascode/common/onboarding/JiraBitbucketOnboarding.test.tsx
- src/react/atlascode/common/onboarding/JiraBitbucketOnboarding.tsx
Only 35-40% of users click on the sign-in button during onboarding. 
One hypothesis is that the text in the onboarding makes users not understand that this is a sign-in screen. Especially when the screen height is small the and the button to sign in is covered up. 
This change is to make the text more clear to the user. 
Manual visual testing
Basic checks:
> During onboarding, use the words "Sign In" 

- src/jira/jqlManager.ts
- src/views/jira/customJqlRoot.ts
- src/views/jira/treeViews/customJqlViewProvider.test.ts
- src/views/jira/treeViews/customJqlViewProvider.ts
- src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.test.ts
- src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.ts
It looks like the event `onDidJQLChange` in jqlManager is never fired, so this is cleaning it up.
Basic checks:
> Cleanup unused onDidJQLChange event

- CHANGELOG.md
- src/bitbucket/bitbucket-cloud/pullRequests.ts
- src/bitbucket/bitbucket-server/pullRequests.ts
- src/bitbucket/model.ts
- src/react/atlascode/common/BasicPanel.tsx
- src/react/atlascode/pullrequest/AddReviewers.tsx
- src/react/atlascode/pullrequest/CommentTask.tsx
- src/react/atlascode/pullrequest/CommentTaskAdder.tsx
- src/react/atlascode/pullrequest/DialogUserPicker.tsx
- src/react/atlascode/pullrequest/EditableTextComponent.tsx
- src/react/atlascode/pullrequest/InlineRenderedTextEditor.tsx
- src/react/atlascode/pullrequest/NestedComment.tsx
- src/react/atlascode/pullrequest/PRBuildStatus.tsx
- src/react/atlascode/pullrequest/PageTaskAdder.tsx
- src/react/atlascode/pullrequest/PageTaskList.tsx
- src/react/atlascode/pullrequest/PullRequestDetailsPage.tsx
- src/react/atlascode/pullrequest/Reviewers.tsx
- src/react/atlascode/pullrequest/SummaryPanel.tsx
This PR is a preview of visual refresh for the plugin. The idea is to keep the Ui for pull request page close to BitBucket UI to make it more intuitive. 
The changes include 
1. Changing the current theme with different colors for section titles and page to a unified background color with some dividers
2. UI Changes around builds section with timestamp
3. UI Changes around reviewers section with a better experience to remove and add reviwer.
4. Task section is moved to side panel and UI changes around it for seamless experience. Replacing old button styles with a better UI experience.
How Has This Been Tested?
Checked by opening several PRs on Bitbucket Cloud and server and tried modifying the sections I have made changes to. Works fine.
How Has This Been Tested?
1.  [Loom Recording …
> Revamp theme and side panel for Pull Request Details Page

- src/atlclients/authStore.ts
#245 Mentions that a user is struggling to get out of a "bad auth" state. They can go through the flow of authentication, but cannot update their credential due to a log: `Not replacing credentials because the existing credentials have a later iat.`
Manually debugging to confirm that it gets set up correctly. Though to be fair, a lot of this code is blackbox to me. 
Basic checks:
> [AUTHENTICATION] Remove IAT and receivedAt checks for OAuth Cred updates - #245 

- src/webviews/components/issue/view-issue-screen/sidebar/StatusTransitionMenu.tsx
Fix bug in DC where view issue page crashes when undefined statusCategory colorName
manual testing
Basic checks:
> No issue/fix status category color fallback

- scripts/githooks/pre-commit
Bug introduced in #274 : if multiple *.ts / *.tsx / *.js / *.jsx are present in the staged area, `npm run lint` is run for each of them!! 😨  
This fixes it.
> Fix pre-commit script for multiple lint runs

- package-lock.json
- package.json
- src/jira/issueForKey.ts
- src/util/online.ts
- src/views/gitContentProvider.ts
The [p-any package](https://www.npmjs.com/package/p-any) was used to retrieve the first promise that resolves from an array of promises.
We don't need a package for that, the native [Promise.any](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any) does exactly that.
> Remove the p-any package

- src/util/featureFlags/client.ts
Problem: Our Statsig client is unable to send exposure events to Statsig even though we are connected
Possible solution:
Add option to explicitly fire exposure/check event through Statsig client. Safe to do so in this context as there is no possibility of false exposure for AA exp
Unfortunately, Statsig does not get our staging events/exposures so need to release to production to see impact.
Basic checks:
> AXON-319: add option to explicitly fire exposure event

- src/bitbucket/bitbucket-cloud/pullRequests.ts
- src/bitbucket/bitbucket-server/pullRequests.ts
- src/bitbucket/model.ts
- src/react/atlascode/pipelines/PipelineSummaryPage.tsx
- src/react/atlascode/pullrequest/PullRequestDetailsPage.tsx
- src/react/atlascode/pullrequest/PullRequestHeader.tsx
- src/react/atlascode/pullrequest/PullRequestHeaderActions.tsx
- src/react/atlascode/pullrequest/PullRequestMainContent.tsx
- src/react/atlascode/pullrequest/PullRequestSideBar.tsx
This PR moves around the components so that not everything is within the PR Details page:
1. It creates new child component files.
2. Moves derived state into the child files instead of creating and passing everything from the top of the page.
3. Adds a new boolean variable in the PR model `draft`: which is not used anywhere yet.
This PR acts as an intermediary PR to avoid big monolith PRs.
Basic checks:
> Refactor PR Details page components and state

- src/react/atlascode/pullrequest/DiffList.tsx
Very small change which changes the cursor from `Edit` to `pointer`.
I used component = button instead of changing the style because, we were using `onClick` and it was more semantical approach to use button instead of a plain link.
> chore: make file diffs appear clickable

- src/webviews/components/issue/PullRequests.tsx
- src/webviews/components/issue/view-issue-screen/sidebar/IssueSidebarCollapsible.tsx
Fix overflow styling for Recent Pull Requests field in Issue Screen sidebar group
Before: 
After: 
Manual testing
Basic checks:
> AXON-327: fix pull requests field in issue view sidebar

- src/analytics.ts
- src/errorReporting.ts
The error telemetry is capturing errors originating from outside of the extension.
For instance, the most frequent errors are coming from the extension `mohamedbenhida.laravel-intellisense-0.2.0`.
Added a filter that filters out Errors not originating from our extension simply analyzing the stack trace. 
Additionally, added a sanitization of the stack trace to remove the os's user name from it.
Basic checks:
> [AXON-329] Fix error telemetry to include only atlascode errors

- src/webviews/components/issue/create-issue-screen/CreateIssuePage.tsx
Repro of Bug: 
1. Create Jira project 
2. Modify the Jira Project to not have one of the "key fields"
3. Checkout and install git sha `47fd65bc2fddc268e79a48457325c728dc708166`
4. Be logged into the Jira Site that hosts that project
5. Create a Jira
6. Get a blank screen 
Manually testing 
Basic checks:
> Fix createIssuePage to handle missing fields

- src/analytics.ts
The old error event is being flooded by telemetry events from v3.4.24, and we had to shut it down immediately to reduce the cost for those unnecessary events.
The telemetry fix is already in place since v3.4.25, but we now want to have a new event name so we only process the ones we need.
> Rename telemetry error event

- package-lock.json
- src/extension.ts
Based on [this thread](https://atlassian.slack.com/archives/C04PR2YE4UC/p1742429892425979), it was discoved that the exposure events were being blocked because the Statsig client was recognizing our extension as a server environment rather than a client. This check is shown in this [code here](https://github.com/statsig-io/js-client-monorepo/blob/05021e3b0ed79e7ae09ded914dff6089561853ec/packages/client-core/src/SafeJs.ts#L13-L25)
As a work around, I defined a window object so the Stastig client can declare us as a client side app and let us send exposure events back to statsig
Test exposures on `atlascode-noop` flag: https://console.statsig.com/LqivKg6ADZZaGczRfBKfX/gates/atlascode-noop/diagnostics
Test exposures in `atlascode_aa_experiment`: …
> AXON-344: add window object

- src/react/atlascode/pullrequest/Reviewers.tsx
Fix squashed reviewer drop down in PR details page
Issue: https://github.com/atlassian/atlascode/issues/324
Before 
After
manual testing PR functionality
Basic checks:
> AXON-346: fix pr reviewers spacing

- CHANGELOG.md
- src/webviews/components/issue/create-issue-screen/Panel.tsx
- src/webviews/components/issue/view-issue-screen/JiraIssuePage.tsx
Made the epic/parent link in issue view nav clickable
Loom: https://www.loom.com/share/85b58288400e4a2ea7ea1dc3ac97ed20?sid=d9a3ddeb-f413-4283-ac2a-66998032d4c3
Basic checks:
> AXON-120: epic/parent link clickable

- __mocks__/p-retry.ts
- package-lock.json
- package.json
- src/util/online.ts
Reverts atlassian/atlascode#327
It looks like the new `p-retry` package is making the extension crashing in debug mode, for some reason.
Reverting to unblock next release.
> Revert "Bump p-retry from 4.6.2 to 6.2.1"

- src/jira/jqlManager.test.ts
- src/jira/jqlManager.ts
- src/views/jira/treeViews/customJqlViewProvider.test.ts
- src/views/jira/treeViews/customJqlViewProvider.ts
With the new Jira panels, we don't need the JQL initialization for every site anymore.
The default query is built ad-hoc for the assigned jira work items panel, and we only need custom JQLs manually configured by the user.
Side effect: users who are upgrading from previous versions will see the default queries appearing in the Custom JQL panel, and they have to delete them manually.
Unfortunately, I think there aren't safest alternatives to this.
Basic checks:
> Remove JQL initialization on Jira site add

- src/views/pullrequest/pullRequestNode.ts
Removes the PR ID prefix added to each PR in the pull request listings view. 
1. This is already a very tight space, and a user cares about the pull request title more than the ID, jira ticket number in the PR
2. The PR ID is not really very useful and can be very long in active repos
3. If needed, it is still available on hover and PR open
> Removes pull request ID from sidebar listing

- CHANGELOG.md
- package.json
- src/analytics.ts
- src/analyticsTypes.ts
- src/bitbucket/terminal-link/createPrLinkProvider.test.ts
- src/bitbucket/terminal-link/createPrLinkProvider.ts
- src/config/model.ts
- src/container.ts
Adds terminal link panel to show when creating pr from terminal that asks whether to create pr in extension or browser
***Only cloud BB***
Added UT + manual testing
Loom: https://www.loom.com/share/6f3224d0bf2942bca271ab651749d979?sid=5f7af610-8c9b-47cf-961c-4a028b38656c
Basic checks:
- [] If Atlassian employee & Bitbucket changes: did you test with DC in mind? [See Instructions](https://www.loom.com/share/71e5d17734a547f68fd6128be6cd760e?sid=835e58a7-1240-498d-b2d7-fa7fdf8ffa36)
> [AXON-348] Bitbucket PR creation terminal integration

- src/analytics.ts
- src/extension.ts
- src/lib/analyticsApi.ts
- src/siteManager.ts
- src/vscAnalyticsApi.ts
The current launched event doesn't track Authentication State. So, adding it in. 
Why is the necessary? 
We need to approximate the number of calls we will make to the notification service. Without knowing the number of auth'ed users who are launching VSCode in a given day, this is hard. 
Added in dataPortal: 
https://data-portal.internal.atlassian.com/analytics/registry/18825?tabIndex=Attributes
Manual debug to confirm that the is<Product>Authenticate works as expected. 
Basic checks:
> Enrich launched event

- CHANGELOG.md
- src/views/jira/treeViews/customJqlViewProvider.test.ts
- src/views/jira/treeViews/customJqlViewProvider.ts
- src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.test.ts
- src/views/jira/treeViews/utils.test.ts
- src/views/jira/treeViews/utils.ts
- src/views/nodes/relatedIssuesNode.test.ts
- src/views/nodes/relatedIssuesNode.ts
- src/views/pullrequest/pullRequestNode.ts
Fixes #372.
Similar issue and fix to #261.
Related Jira issues in Pull Requests need to have unique IDs for different PRs so the same item can show up multiple times for different pull requests.
Basic checks:
> [AXON-362] Fixed already registered id error when showing PR related issues

- .gitignore
- .vscode/settings.json
Small ways-of-working improvement - we now format file automatically on save after editing. Returning from the other project, this was bugging me quite a bit ;D
The configuration for this is added to workspace settings, which are now no longer `.gitignore`-d
Edited some files, then saved them ;) Observed the expected behavior
Basic checks:
> [AXON-374] chore: add format-on-save to the workspace settings

- src/analytics.ts
- src/atlclients/clientManager.ts
- src/bitbucket/httpClient.ts
- src/errorReporting.test.ts
- src/errorReporting.ts
- src/logger.ts
- src/views/jira/treeViews/utils.test.ts
- src/views/jira/treeViews/utils.ts
- testsutil/miscFunctions.ts
This PR:
- fixes a couple of error messages to not include variable parameters
- adds a new field in the error event to carry extra params
- other minor fixes
> Refined error telemetry data

- src/bitbucket/terminal-link/createPrLinkProvider.test.ts
- src/bitbucket/terminal-link/createPrLinkProvider.ts
Add `notificationChangeEvent` to the banner notifcation flow to signify that the banner has appeared before the user has taken any action
> Add notif change event for any time banner appears

- CHANGELOG.md
- HOMEPAGE.md
- package.json
- Drop the "Labs" from our name
- Move Atlassian from back of title to front of title to match the short name "Atlassian For VS Code" more. 
- TBD: Used & per our Word Engineer Collin
- Approved List: Trevor (HOE), Laurena (PMM)
- https://www.reddit.com/r/vscode/comments/16lzht9/comment/k18ne7t/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
> AXON-301: Drop labs from extension title

- src/extension.ts
- src/util/featureFlags/features.ts
- src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.test.ts
- src/views/jira/treeViews/jiraAssignedWorkItemsViewProvider.ts
- src/views/notifications/bannerDelegate.ts
Badges are out in production now. 
Data indicates that it increases the rate of a no-auth launch -> Authentication by a 2x factor. 
Removing FF so we can accelerate the change faster. 
Note: The FF strategy is enforcing bake times that are too slow.
> AXON-405: Remove FF for badges and banners

- .vscode/launch.json.example
- package-lock.json
- package.json
- src/atlclients/authInfo.ts
- src/commands.ts
- src/constants.ts
- src/container.ts
- webpack.extension.dev.js
- webpack.extension.prod.js
- webpack.react.dev.js
- webpack.react.prod.js
This cleans up leftovers from the old E2E infrastructures:
- `chai` and `vscode-extension-tester` packages
- `test login` and `test logout` commands
- usage of `ATLASCODE_TEST_USER_API_TOKEN`
- unused code
> Clean-ups after changing the E2E framework

- package-lock.json
- package.json
- src/util/featureFlags/featureFlagClient.ts
Update `@atlaskit/feature-gate-js-client` package after statsig client version bump
> This update includes the statsig exposures override for non-window environments
> [AXON-293] update fg client and add new init options

- e2e/Dockerfile
In the nightly release build, we package the code with the correct version (and not 0.0.0), so the Dockerfile command needs to account for that.
> Fixed E2E tests in nightly build

- .github/workflows/build.yaml
- .github/workflows/release-nightly.yaml
- .github/workflows/release.yaml
`npm ci` is generally faster than `npm install` because it installs packages directly from the `package-lock.json` file without checking for updates or modifying it. This makes `npm ci` particularly efficient for clean installations in automated environments.
> Use npm ci in pipeline

- jest.config.ts
- src/siteManager.test.ts
- tsconfig.json
For a while now, we've been using relative paths in our modules to avoid errors in tests along the lines of this:
This PR slightly changes jest config to where it now accepts `src/` paths
A bunch of tiresome trial and error ;)
Basic checks:
> [AXON-385] chore: fix jest config to work with src/ paths

- src/onboarding/onboardingQuickPickManager.test.ts
- src/onboarding/onboardingQuickPickManager.ts
- src/onboarding/utils.ts
Changed the onboarding modal text/copy to be more concise and have better readability
Modal: 
Basic checks:
> fix copy to be more concise

- src/onboarding/onboardingQuickInputManager.ts
- src/onboarding/onboardingQuickPickManager.test.ts
- src/onboarding/onboardingQuickPickManager.ts
- src/onboarding/utils.ts
Added dismiss button on onboarding for a visible way for a user to ignore
Look at top right:
Manual tests
Basic checks:
> add dismiss button

- src/react/atlascode/startwork/StartWorkPage.test.tsx
- src/react/atlascode/startwork/StartWorkPage.tsx
- src/react/atlascode/startwork/branchNameUtils.ts
This is the change that fixes the following issue:
During starting of a task, which will lead me to create and checkout branch, the branch name will always have double dash if my task make use of square bracket:
task name: [module] create function xxx
generated branch name module--create-function-xxx
the fix will change for the name to be module-create-function-xxx
There is a test written for that in the PR
Basic checks:
> [AXON-163] Remove dashing duplicates and trailing dashes

- src/bitbucket/bitbucket-server/pullRequests.ts
Fix of the issue when hyperlink for commit fails to open. The issue is related to Server Bitbucket. We don’t pass the url for commit. That’s why when  the url is undefined or malformed VS Code's webview tries to interpret this as a local resource path.
I’ve reproduced the issue by hardcoding the url to be undefined for Bitbucket Cloud. 
Basic checks:
> FIX: fix issue when commit url is undefined

- src/react/atlascode/startwork/StartWorkPage.tsx
✅ Fixed the issue with branch prefix always set to the first one in list ( default one ).  
❓ The reason of the issue: in `handleBranchTypeChange` we set up the branch type and call the `buildBranchNameView` func.  `buildBranchNameView` is in deps list in useEffect, where we again rewrite branch type and set it up to the first value in the list ( initial setup ).
Screenrecord with fixed behaviour: 
https://github.com/user-attachments/assets/2fbf1c72-7613-499c-831a-51c63bfa8299
Basic checks:
> AXON-525: fix issue with prefix dropdown

- resources/html/reactWebview.html
- src/react/atlascode/rovo-dev/RovoDevCodeHighlighting.css
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/rovo-dev/rovoDevWebviewProvider.ts
- src/webview/common/getHtmlForView.ts
- webpack.react.prod.js
This PR defines the css styling for code highlighting with the `.vscode-dark` directive to automatically adjust it to a change of light and dark themes.
It doesn't follow the same theme's color, but it simply sets two different set of colors for light and dark.
> [Rovo Dev] Auto-adjust code highlighting on changed theme

- e2e/helpers.ts
- e2e/helpers/updateIssueFields.ts
- e2e/tests/playwright.spec.ts
- e2e/wiremock-mappings/mockedteams/addComment.json
Added the e2e test that covers adding the comment flow. The author of the comment is checked as well
[video.webm](https://github.com/user-attachments/assets/0e4395e2-99b0-4fa6-b758-51210ecf0aeb)
Basic checks:
> AXON-455: add e2e test for comment on jira flow

- e2e/tests/jira/createIssue.spec.ts
- e2e/wiremock-mappings/mockedteams/createIssue.json
- e2e/wiremock-mappings/mockedteams/project.json
- e2e/wiremock-mappings/mockedteams/search-project.json
Added e2e test for create an issue via side pannel flow:
✅  Authenticate with Jira using the existing helper function
✅ Click the "Create Jira issue" button in the side panel
✅ Check that create issue form is loaded with the heading "Create work item"
✅ Click and fill in the summary field with "Test Issue Created via E2E Test"
✅ Scroll the Create button into view to ensure it's visible
✅ Click the Create button to submit the form
✅ Scroll the success message into view
✅ Verify that "Issue Created" text appears and new issue key "BTS-7" is displayed
[CreateIssue.webm](https://github.com/user-attachments/assets/c81660c7-e20d-4ca6-8e4b-066504574a32)
Basic checks:
> AXON-452: add e2e test for create an issue flow

- CHANGELOG.md
- src/react/atlascode/startwork/StartWorkPage.tsx
Added trailing slash to custom prefix 
**Expected behaviour** -> trailing slash is added to custom prefix as  described on Settings page
Current behaviour: 
https://github.com/user-attachments/assets/a89d698e-c324-4bc9-b17f-37f6f528d662
Behaviour with fix:
https://github.com/user-attachments/assets/ce88d077-682f-4ed2-9b5a-01135467b865
Basic checks:
> AXON-528: add trailing slash to custom prefix

- src/react/atlascode/rovo-dev/common.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/rovoDevViewMessages.tsx
- src/rovo-dev/rovoDevPullRequestHandler.test.ts
- src/rovo-dev/rovoDevPullRequestHandler.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
- src/rovo-dev/rovoDevWebviewProviderMessages.ts
This change adds a working bit of logic to create PRs right from the rovodev changeset:
I've iterated on the PR logic and the look and feel of this since the PoC, but this is still somewhat happy-path oriented
Manually, against bitbucket and github! :)
Basic checks:
> [AXON-521] Add PR creation functionality to rovodev view

- e2e/compose.yml
- e2e/helpers.ts
- e2e/sslcerts/generate-certs.sh
- e2e/tests/bitbucket/authFlowCloud.spec.ts
- e2e/tests/bitbucket/authFlowDC.spec.ts
- e2e/wiremock-mappings/bitbucket/access-token-bb-cloud.json
- e2e/wiremock-mappings/bitbucket/build-capabilities-bb-dc.json
- e2e/wiremock-mappings/bitbucket/get-user-bb-cloud.json
- e2e/wiremock-mappings/bitbucket/get-user-bb-dc.json
- added new WireMock service for Bitbucket testing ( `wiremock-bitbucket` )
- added certificate generation for wiremock-bitbucket service
- added mocked API responses related to auth flow
- extracted duplicated logic into `openAtlassianSettings()` method
- added e2e tests for auth flow in Bitbucket Cloud and Bitbucket DC
Screenrecord for Bitbucket Cloud auth flow:
[cloud.webm](https://github.com/user-attachments/assets/e76444be-a441-4707-958a-fc12fe1c866e)
Screenrecord for Bitbucket DC auth flow: 
[dc.webm](https://github.com/user-attachments/assets/54ff3d32-ff37-462a-98be-8e89984d1055)
Basic checks:
> AXON-536: add e2e tests for bb DC and Cloud auth flow

- src/rovo-dev/rovoDevWebviewProvider.ts
When the user undoes one or more files, we should inform Rovo Dev about the reverts within the next prompt.
> [AXON-587] Inform Rovo Dev of reverted files

- src/react/atlascode/rovo-dev/rovoDevView.tsx
Changes the Stop button from a 'Pause' icon to a 'Cross' icon, to avoid confusion.
> [Rovo Dev] Changes the Stop button from a 'Pause' icon to a 'Cross' icon

- package.json
Currently, Docker containers used during e2e test runs are not automatically removed after the tests complete. This leads to an accumulation of unused containers over time 
Goal is to ensure that containers are properly cleaned up to prevent resource leakage & maintain a clean local env
Basic checks:
> AXON-592: cleaned up containers used during e2e test run

- src/react/atlascode/rovo-dev/common.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/rovoDevViewStyles.tsx
Messages were buffered in a `currentResponse` state before being finalized and added to the `chatHistory` state.
This indirection isn't really necessary, and we can write directly into the chatHistory, removing extra state, dom elements, and logic.
Basic checks:
> [AXON-606] [Rovo Dev] Removed currentResponse state and simplified rendering

- src/react/atlascode/rovo-dev/common.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/rovoDevViewMessages.tsx
- src/react/atlascode/rovo-dev/rovoDevViewStyles.tsx
- src/react/atlascode/rovo-dev/utils.tsx
- src/rovo-dev/rovoDevApiClient.test.ts
- src/rovo-dev/rovoDevApiClient.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
First iteration of the error-handling scenario.
This PR implements the UI for displaying an error message in the chat, which is displayed every time the provider sends an 'error' to the view.
The error can be [retriable](https://english.stackexchange.com/questions/305273/retriable-or-retryable) or not, which will determine if the `Try again` button will be rendered or not:
Trying again creates a new prompt where we tell the agent that the previous response was interrupted unexpectedly due to an error, we remind the agent what the previous prompt was, and we ask the agent to continue from where it was interrupted.
> [AXON-574][Rovo Dev] Detect error mid-response and provide a 'Try again' button

- src/constants.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
We can configure the port, but not the host for rovodev at the moment. For some launch configurations, we need that to be different too (e.g. when running in docker). This change allows for that to be done via environment
Manually, ran the extension with a bunch of different values in `ROVODEV_HOST` :)
Basic checks:
> [AXON-594] Make rovodev host configurable from environment

- src/webviews/jiraIssueWebview.ts
Looked to see if it affected votes, watchers, or avatarUrl on page but it did not. Now the user is not reset and the url to the image should not disappear.
- Address the bug where the currentUser would be reset to undefined when we navigate to and from a user.
The currentUser would reset make the user undefined and have no avatarURL after navigating back to the issue. Now we do we not have this reset.
- No particular test but now the image does not reset upon reloading of the user.
- This particular value is not used to fetch any data anywhere else in jiraIssueWebview.ts
Basic checks:
> Addressed the bug found in jiraIssueWebview for currentUser reset

- CHANGELOG.md
- src/lib/ipc/fromUI/startWork.ts
- src/lib/webview/controller/startwork/startWorkWebviewController.ts
- src/react/atlascode/startwork/StartWorkPage.tsx
- src/webview/startwork/vscStartWorkActionApi.ts
✅  Fixed a bug when transitioning Jira issues from 'Start work', which doesn't refresh the issues panels
- After the user has started working on the ticket, its status changes to the corresponding one in the sidebar.
After fix:
https://www.loom.com/share/2d0b780d02fd4980a0530385b6e7e577?sid=381fc860-4108-46fd-bff5-0017deb8907b
Basic checks:
> Axon-351 jira item to in progress via start work still to do in the panel

- CHANGELOG.md
- src/views/jira/searchJiraHelper.test.ts
- src/views/jira/searchJiraHelper.ts
- src/webviews/createIssueWebview.test.ts
- src/webviews/createIssueWebview.ts
This PR slightly changes the logic of filling in the site and project fields on the create issue page.
After this change, the site or project where most of the assigned Jira issues originate will be set as the default if the user opens the page for the first time.
Basic checks:
> AXON-18 Creating a JIRA issue should default to the most relevant site

- src/react/atlascode/rovo-dev/RovoDev.css
- src/react/atlascode/rovo-dev/common/common.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/technical-plan/CodePlanButton.test.tsx
- src/react/atlascode/rovo-dev/technical-plan/CodePlanButton.tsx
- src/react/atlascode/rovo-dev/utils.tsx
Added button which allows for user to execute the technical plan generated by the agent
Button persists only if there is an active code plan and does not appear if any other types of responses
Demo:
https://www.loom.com/share/8d9a6f0f8f424a019f34caa4ac67454b?sid=1750132a-6beb-4435-9526-10a7066a7722
Added simple UT + manual tests
Basic checks:
> [AXON-582]: Implement code plan button

- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/rovoDevViewStyles.tsx
This change adds the CSS property `field-sizing: content` to allow the text area for the prompt query to resize automatically based on its content.
> [AXON-621][Rovo Dev] Resize text area on overflow

- .github/workflows/release-nightly.yaml
- .github/workflows/release.yaml
- package.json
In release pipeline we shouldn't collect nor check the UT coverage, as failing the coverage threshold is not something that should block the release.
> Skip test coverage collection in release pipeline

- src/react/atlascode/rovo-dev/RovoDev.css
- src/react/atlascode/rovo-dev/common/common.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/utils.tsx
Updated the modified file parsing so files are correctly counted as deleted.
DEMO:
https://www.loom.com/share/8d56c85bd9114945a0fce6e11e281921?sid=6cd45810-4d2d-4069-8480-8b9c4d307c73
Manual tests
Will add UT for Updated File Component in following PR
Basic checks:
> [AXON-513]: Updated file component now tracks deletions

- src/react/atlascode/rovo-dev/common/common.tsx
- src/react/atlascode/rovo-dev/messaging/ChatHistory.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/rovoDevViewMessages.tsx
- src/rovo-dev/rovoDevPullRequestHandler.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
- src/rovo-dev/rovoDevWebviewProviderMessages.ts
In-progress PR work, now it looks like this:
The footer appears and disappears as expected, leaving behind the success/error message :D
This is a intermediate state of things - styling, form, and some other stuff is TBD
Big thanks to @cabella-dot <3
Extensive manual tests with anime writing involved (heavily)
Basic checks:
> [AXON-577] Change the Create PR button to appear in chat

- src/react/atlascode/rovo-dev/RovoDev.css
- src/react/atlascode/rovo-dev/rovoDevLanding.tsx
The Rovo Dev landing page is not supposed to be shown in BBY, so disabling it there.
Also, added a `cursor: pointer` style for Rovo Dev buttons.
> [Rovo Dev] Remove landing in BBY and fix buttons' pointer style

- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/utils.tsx
- src/rovo-dev/rovoDevWebviewProvider.ts
The technical plan is wasn't being rendered because it was expected from the `content` field of the response as a string, but it's actually an object which goes to the `parsedContent` field instead.
> [AXON-701][Rovo Dev] Fix Deep plan not being rendered

- src/react/atlascode/rovo-dev/RovoDev.css
- src/react/atlascode/rovo-dev/common/common.tsx
- src/react/atlascode/rovo-dev/create-pr/PullRequestForm.tsx
- src/react/atlascode/rovo-dev/messaging/ChatHistory.tsx
- src/react/atlascode/rovo-dev/messaging/ChatMessageItem.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/utils.tsx
Added rendering for `retry-prompt` message to indicate that a tool call has failed.
^^ Signed off by adam btw
manual tests
Basic checks:
> AXON-670: add rendering for retry-prompt

- CHANGELOG.md
- src/webviews/components/issue/create-issue-screen/CreateIssuePage.tsx
- src/webviews/createIssueWebview.ts
✅ Fixed a bug - after creating a new Jira issue doesn't see this issue in the sidebar
After the user creates a new ticket, this ticket doesn't appear in the sidebar.
Basic checks:
After fix:
https://www.loom.com/share/b0939cb0f1c14b6aa19fd9b274572295?sid=7a967371-156c-44de-afca-03a30d5a9f60
> AXON-675: Update sidebar after issue was created

- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/rovoDevViewMessages.tsx
- src/rovo-dev/rovoDevWebviewProvider.ts
Quick follow-up for the context PR - correctly set initial state of the context bar
When the user opens up the webview, we:
* fire an event to the extension process
* look at the open editors and whatnot
* send an update back right away
Piggy-backing on the `Initialized` event turned out to be too slow 😱 
> [AXON-522] Force correct initial state for the prompt context

- jest.config.ts
- src/analytics.test.ts
- src/analytics.ts
- src/rovo-dev/performanceLogger.test.ts
- src/rovo-dev/performanceLogger.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
- src/util/perf.test.ts
- src/util/perf.ts
This change implements the Rovo Dev performance telemetry events, measuring:
- time to respond with the first byte
- time to respond with the first message
- time to respond with a technical plan
- time to respond with the last message
> [AXON-721][Rovo Dev] Fire perf telemetry events

- package.json
- src/commands.ts
- src/container.ts
- src/rovo-dev/rovoDevDecorator.ts
- src/webviews/jiraIssueWebview.ts
Add a little annotation showing the prompt and default keybinding to send something to rovodev chat
Notably, we can only use the default keybinding because it seems that there's no way to dynamically get it through the VSCode API :(
> [AXON-522] Add annotation instruction w/ keyboard shortcut

- src/lib/ipc/toUI/onboarding.ts
- src/lib/ipc/toUI/pipelineSummary.ts
- src/lib/ipc/toUI/pullRequestDetails.ts
- src/lib/webview/controller/pipelines/pipelineSummaryWebviewController.ts
- src/react/atlascode/config/configController.ts
- src/react/atlascode/messagingApi.ts
- src/react/atlascode/onboarding/onboardingController.ts
- src/react/atlascode/pipelines/pipelineSummaryController.ts
- src/react/atlascode/pullrequest/createPullRequestController.ts
- src/react/atlascode/pullrequest/pullRequestDetailsController.ts
- src/react/atlascode/rovo-dev/create-pr/PullRequestForm.test.tsx
- src/react/atlascode/rovo-dev/create-pr/PullRequestForm.tsx
- src/react/atlascode/rovo-dev/messaging/ChatStream.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/rovoDevViewMessages.tsx
- src/react/atlascode/startwork/startWorkController.ts
- src/rovo-dev/rovoDevWebviewProviderMessages.ts
The core of this change is in `src/react/atlascode/messagingApi.ts`.
Thanks to this improved typings, when calling `postMessagePromise` the return type is now inferred from the value of the `waitForEvent` argument:
| <img width="570" height="349" alt="image" src="https://github.com/user-attachments/assets/f435c2ba-9879-4e2c-908a-c7c0e5cfb2ac" /> | <img width="521" height="284" alt="image" src="https://github.com/user-attachments/assets/45412b89-4ef9-4902-9e70-024be32194ee" /> |
|---|---|
> Improve useMessageApi typings

- src/react/atlascode/rovo-dev/RovoDev.css
- src/react/atlascode/rovo-dev/prompt-box/updated-files/ModifiedFileItem.tsx
- src/react/atlascode/rovo-dev/prompt-box/updated-files/UpdatedFilesComponent.test.tsx
- src/react/atlascode/rovo-dev/prompt-box/updated-files/UpdatedFilesComponent.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
Disable total and specific keep/undo buttons when rovo dev is still responding
Updated UT
manual tests
Basic checks:
> [AXON-728] Keep/Undo buttons disabled when generating response

- package-lock.json
- package.json
- src/webviews/components/issue/InlineSubtaskEditor.tsx
Upgrade react-editext to 7.0.0
This is a subtask for our main goal of [upgrading the React version](https://hello.atlassian.net/wiki/spaces/AIDO/pages/5629249869/Upgrade+React+estimation+strategy).
Basic checks:
> AXON-703: upgrade react-editext to 7.0.0

- e2e/Dockerfile
- e2e/README.md
- e2e/compose.yml
- package.json
This change adds a new script to package.json that starts a code-server without launching the e2e tests. And allows dev to explore the testing environment.
Basic checks:
> AXON-689 Add ability to access the code-server from host machine

- jest.config.ts
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/rovo-dev/rovoDevWebviewProvider.ts
- src/rovo-dev/rovoDevWebviewProviderMessages.ts
When replay would occur, it would not send that the response is generating to the frontend and it would send `CompleteMessage` event to the frontend which changes the state to `Waiting`. This messed up the streaming because we would not group messages if the state is still waiting for prompt. Now when replay is triggered or there is a pending prompt, the state is changes to `GeneratingResponse` so the stream can act correctly 
manual tests
> [AXON-730] Fix state error when 'replay' and 'pending prompt'

- jest.config.ts
- src/react/atlascode/rovo-dev/RovoDev.css
- src/react/atlascode/rovo-dev/prompt-box/updated-files/ModifiedFileItem.test.tsx
- src/react/atlascode/rovo-dev/prompt-box/updated-files/ModifiedFileItem.tsx
- src/react/atlascode/rovo-dev/prompt-box/updated-files/UpdatedFilesComponent.test.tsx
- src/react/atlascode/rovo-dev/prompt-box/updated-files/UpdatedFilesComponent.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/rovoDevViewMessages.tsx
- src/react/atlascode/rovo-dev/tools/ToolReturnItem.tsx
- src/rovo-dev/rovoDevWebviewProvider.ts
When undoing a newly created file, the new file should simply be deleted.
When undoing a modified or deleted file, copying over the cache into the "new file" is still correct.
Basic checks:
> [AXON-686][Rovo Dev] Fix Undo does not remove newly created files

- .vscodeignore
Add `codicon` distribution to vsix, based on this:
https://github.com/microsoft/vscode-extension-samples/issues/692
|-|-|
|  <img width="321" height="146" alt="image" src="https://github.com/user-attachments/assets/58fb4939-97bf-41e2-88bb-45684fbbc35a" /> | <img width="272" height="152" alt="image" src="https://github.com/user-attachments/assets/6f830ef4-4ac8-436f-a451-1ca6ccc64f4e" /> |
This was very specifically a problem in the vsix distribution, not when running the debugger
`npm run extension:install`
Basic checks:
> [AXON-739] Add codicon distribution to vsix

- jest.config.ts
- src/commands.ts
Quick fix to add multiple bits of selection to context at once when multi-selection is used in the editor
```
m a n u a  l l y
```
Basic checks:
> [AXON-741] Add all bits in multiselection to context if needed

- src/react/atlascode/rovo-dev/RovoDev.css
- src/react/atlascode/rovo-dev/create-pr/PullRequestForm.tsx
- src/rovo-dev/rovoDevWebviewProvider.ts
- src/rovo-dev/rovoDevWebviewProviderMessages.ts
Added better error handling for the pr creation functionality
* added gitErrorCode to give better understanding of what went wrong
Fixed input border to be styled with vscode variables when focused
success:
error:
m a n u a l
Basic checks:
> [AXON-767] Added better error handling for pr creation

- src/atlclients/authStore.ts
- src/atlclients/clientManager.test.ts
- src/atlclients/clientManager.ts
- src/constants.ts
Currently, after 401/403 error, we mark the auth state as Invalid, block client creation, and show the popup with real error ( not meaningful for user ) - cannot get client for: [product]. In this PR I've updated cannot get client error messages to more meaningful:
- `Unable to connect to ${site.product.name}. Please sign in again to continue.` for cases when invalid credentials during client creation were used
- `Your ${site.product.name} session has expired. Please sign in again to continue.`  in case of token refresh failure
Basic checks:
> AXON-750: change cannot get client error message to more meaningful

- src/react/atlascode/rovo-dev/create-pr/PullRequestForm.test.tsx
- src/react/atlascode/rovo-dev/create-pr/PullRequestForm.tsx
- src/react/atlascode/rovo-dev/messaging/ChatStream.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/rovoDevViewMessages.tsx
- src/rovo-dev/rovoDevPullRequestHandler.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
- src/rovo-dev/rovoDevWebviewProviderMessages.ts
With this change, the behaviour of the Create PR button in rovodev chat is conditional on the overall state of the workspace as seen by the VSCode git integration - as opposed to the changes we track in the chat drawer
This is more in line with our original intention - but there are some interesting implications, please refer to the loom in #axon on this :)
Basic checks:
> [AXON-742] Make PR button tied to the broader workspace state

- CHANGELOG.md
- src/webviews/components/issue/view-issue-screen/JiraIssuePage.tsx
Quick fix for #665 - let's treat the `issuetype` field as optional for the purpose of epic types
Manually - although I couldn't reproduce the original issue on the Jira Server instances available, nor in the cloud :(
Basic checks:
> GH#665 - treat selectFieldOptions['issuetype'] as optional

- src/react/atlascode/rovo-dev/RovoDev.css
- src/react/atlascode/rovo-dev/common/common.tsx
- src/react/atlascode/rovo-dev/messaging/ChatMessageItem.tsx
- src/react/atlascode/rovo-dev/prompt-box/promptContext/promptContextCollection.tsx
- src/react/atlascode/rovo-dev/prompt-box/promptContext/promptContextItem.tsx
Fixed the tool icon placement to be `flex-start` instead of center for larger tool returns
Fixed prompt context margin when it is in the chat so the spacing is consistent
Removed `linkify` which registered file names as href links in markdown
Manual
Basic checks:
> [NO-ISSUE] Fix tool icon placement

- src/analyticsTypes.ts
- src/react/atlascode/startwork/v3/StartWorkPageV3.tsx
- src/react/atlascode/startwork/v3/components/CreateBranchSection.test.tsx
- src/react/atlascode/startwork/v3/components/CreateBranchSection.tsx
- src/react/atlascode/startwork/v3/components/TaskInfoSection.test.tsx
- src/react/atlascode/startwork/v3/components/TaskInfoSection.tsx
- src/react/atlascode/startwork/v3/components/UpdateStatusSection.test.tsx
- src/react/atlascode/startwork/v3/components/UpdateStatusSection.tsx
- src/react/atlascode/startwork/v3/components/index.ts
- src/react/atlascode/startwork/v3/types.ts
Prepares the StartWork Page V3 layout.
**Note**: Layout-only preparation - functionality will be implemented in the next PR.
**Result**:
**How to test:**
Create `.env`
Add `ATLASCODE_FF_OVERRIDES=atlascode-start-work-v3=true`
Basic checks:
> AXON-738: Start work redesign: Layout

- .github/workflows/build.yaml
- Split e2e and unit test jobs to run in parallel, reducing average build time from 14:30 to 9:30 (~30%)
- Introduced fail-fast strategy: if one of the test jobs fails, the other is auto cancelled
- Added step to upload e2e artifacts for easier debugging in case of failures
Before: 
<hr/>
After:
e2e artifacts:
<hr/>
@marcomura please go to Repository settings, find rule, click Edit and instead of 'build' add 'lint', 'tests(unit)', 'tests(e2e)'
> [AXON-772, AXON-788]: Reconfigure GitHub's build pipeline to run in parallel unit tests and E2E tests

- src/rovo-dev/rovoDevWebviewProvider.ts
- Bug: When replaying messages that had <context> on them, that would show in the UI. 
- Fix: when inspecting the user message, if the <context> tags are there, remove them and the content within them 
Manual. The regex was tested with the help of Copilot on several different cases. 
- The pretty "file tokens" don't show up on the replay.
> Rovo Dev: Hide context on replay

- CHANGELOG.md
- src/webviews/components/issue/view-issue-screen/sidebar/IssueSidebarButtonGroup.tsx
Fixed status button in smaller screen size
Before/After: https://www.loom.com/share/5704269f572b44fabf1a837e95ec94f7?sid=d74ae920-a7cb-4e49-a939-fad430aa558d
Basic checks:
> Axon 322 status button is clipped

- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/rovo-dev/rovoDevWebviewProvider.ts
Now sends `Sent Prompt` signal to view regardless of ``suppression so all messages will change the state to `Generating Response`
This allows for pending prompt + replay messages to be rendered correctly
Manually
Basic checks:
> [AXON-810] Fix replay stream bug

- src/react/atlascode/rovo-dev/rovoDevView.tsx
Reorder error message placement so Error message is at end of chat stream
Manual 
Basic checks:
> [AXON-784] Fix error message placement in chat

- CHANGELOG.md
- src/atlclients/loginManager.ts
- src/lib/webview/controller/config/configWebviewController.ts
- src/siteManager.ts
**Problem**
There was a race condition occurring during the authentication process when connecting multiple instances simultaneously. The issue was in the `LoginManager.saveDetails()` method where sites were being added to the SiteManager individually within a `Promise.all` loop, causing potential race conditions and inconsistent state. 
**It was causing the different amount of connected instances.** 
**Root Cause**
`this._siteManager.addSites([siteInfo])` was called inside the Promise.all map function, meaning multiple calls to addSites could occur concurrently
**Solution**
Move the site addition outside the parallel execution and add all sites at once after all credentials have been saved
**Additional Improvements**
- Made cloud authentication call await to properly handle async errors …
> AXON-835: fix race condition issue while connecting instances

- src/atlclients/authStore.ts
- src/webview/config/vscConfigActionApi.test.ts
- src/webview/config/vscConfigActionApi.ts
The `getSitesWithAuth()` method in `vscConfigActionApi` was making redundant authentication calls for sites that shared the same credentialId. This commonly occurs in OAuth scenarios where a single authentication token provides access to multiple Jira/Bitbucket sites.
**Performance Impact:**
- Multiple unnecessary OAuth token refresh calls during config page loads
- Redundant getAuthInfo() calls for sites with identical credentials
- Slower UI loading times due to serial authentication checks
**Fix:**
- Implemented credential-based deduplication in getSitesWithAuth() to eliminate redundant authentication calls
Also, removed unused newTokens variable
Basic checks:
> AXON-777: remove extra calls to get auth info

- src/rovo-dev/responseParser.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
During 'Replay' mode, we don't need the response to be streamed back progressively.
In fact, we'd like it to be rendered as fast as possible.
With this change, when we are in Replay mode, we are reconstructing the entire part-kind `text` message back before being sent to render.
> [AXON-854] Rovo Dev: merge the text chunks while in Replay

- src/siteManager.test.ts
- src/siteManager.ts
In `siteManager`, we now track the "primary site" - one of the Jira Cloud sites which we will use for feature gating processes down the line. This supports both OAuth and API token auth sites
We also now distribute the primary site as part of the `siteManager` update event - and it's available globally through `Container.siteManager.primarySite`
This update introduces the site resolution and makes it available, a follow-up change will hook it into the FeatureGate machinery
Manually - by flipping through different authentication types and edge cases ;)
Basic checks:
> [AXON-849] Enable primary site evaluation in siteManager

- package-lock.json
- package.json
- src/container.ts
- src/extension.ts
- src/rovo-dev/rovoDevProcessManager.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
1. **TCP port**
Currently, the ports are assigned to workspaces using a globalState map, creating an association that was kept forever.
This has the main problem that ports were not checked for availability, and the process will fail if the port is already in use.
With this change, Rovo Dev will attempt to start the service on the first available port of the configured range.
2. **Process management**
Currently, there is a very rudimental logic to handle multiple folder in a workspace, spawning a Rovo Dev process for each of the folder.
With this change, we remove the support for multiple folders, and we spawn a single Rovo Dev instance for the first folder being opened by the workspace.
In the future we may want Rovo Dev to natively support multiple folders in a single instance.
> [AXON-847] Rovo Dev: Improvements in tcp ports and process management

- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/rovo-dev/rovoDevWebviewProvider.ts
- src/rovo-dev/rovoDevWebviewProviderMessages.ts
Now passing a field to UI saying if a tool-return is from the replay
if it is, it will not be counted in the modified files drawer
manually
Basic checks:
> AXON-857: modified files drawer is not updated on replay

- package.json
- src/commandContext.ts
- src/commands.ts
- src/constants.ts
- src/container.ts
Debug-only commands to log in and out of sites. No effect on the properly distributed version of the extension
Manually - see loom in #axon
Basic checks:
> Add debug-mode only commands to speed up development

- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/rovo-dev/responseParser.ts
- src/rovo-dev/rovoDevApiClient.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
- src/rovo-dev/rovoDevWebviewProviderMessages.ts
This change handles the special prompts `/clear` and `/prune`, for which Rovo Dev responds with custom messages.
On `clear` response, we clear the chat.
On `prune` response, we simply display the message information in the chat.
> [AXON-863, AXON-864][Rovo Dev] Handle clear and prune commands

- src/react/atlascode/rovo-dev/rovoDevView.tsx
Updated the logic for moving the current messages into the chat history deterministically between `setCurrentState` and `finalizeResponse`.
> [Rovo Dev] Fix chat error after response finishes

- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/rovo-dev/rovoDevWebviewProvider.ts
Fixed a bug that prevents 'Create new session' to work right after the previous response was cancelled.
> [AXON-892][Rovo Dev] Fix Create new session not working after cancellation

- src/react/atlascode/rovo-dev/rovoDevView.tsx
Changed error/warning/info handing logic so it will be rendered within the response and will not stop the current response.
Demo: https://www.loom.com/share/ac66d37c1a064f3da684ad09bde82a93
manually
Basic checks:
> AXON-883: errors now appear in the response

- src/atlclients/authStore.ts
- src/atlclients/responseHandlers/JiraPKCEResponseHandler.ts
- src/jira/fetchIssue.test.ts
- src/jira/fetchIssue.ts
- src/jira/issuesForJql.test.ts
- src/jira/issuesForJql.ts
- src/jira/settingsManager.test.ts
- src/jira/settingsManager.ts
- src/webviews/jiraIssueWebview.test.ts
- src/webviews/jiraIssueWebview.ts
1. This PR updates the `softRefreshOauth` logic to prevent duplicate concurrent refresh calls for the same credential key. Previously, if multiple requests ( from several connected instances or from several places in app where we need fresh credentials ) were made with the same key, each would initialize its own refresh, potentially causing 403 errors. 
In this PR Promise caching is added, so only one refresh request is executed, while all parallel callers await the same promise. 
2. Added some optimization for Jira field fetching process to reduce redundant API calls to Jira
3. Added missing `await` for `saveAuthInfo` method, removed unnecessary manual array construction in `accessibleResources` method
Basic checks:
> AXON-840: cleanup auth flow from extra calls

- webpack.react.dev.js
We've just caught a situation where `npm run compile` succeeds, but `npm run devcompile` fails on css chunk ordering warnings:
Arguably, this is _very_ undesirable - if the regular build succeeds, the `devcompile` should succeed as well.
To prevent this in the future, let's prevent css ordering warnings when webviews are being compiled
Did a before-and-after on a broken `main`
Basic checks:
> chore: ignore css chunk order warnings in devcompile

- CHANGELOG.md
- src/webviews/components/issue/view-issue-screen/mainpanel/ChildIssuesComponent.test.tsx
- src/webviews/components/issue/view-issue-screen/mainpanel/ChildIssuesComponent.tsx
- src/webviews/components/issue/view-issue-screen/mainpanel/IssueMainPanel.tsx
- src/webviews/jiraIssueWebview.ts
Fixed the issue but still need to test with server
- Fixed the bug where we created an epic from the create issue page and could not see the epic children nor create any.
- Also made the React components easier to read and more general for child-parent types in Cloud and DC.
- Tested via Cloud on Jira instance. 
- Testing still needed on cloud
Basic checks:
> Fixed issue with create and epics

- src/react/atlascode/rovo-dev/RovoDev.css
- src/react/atlascode/rovo-dev/prompt-box/prompt-input/utils.tsx
Was set to 12px for some reason, now fixed to 13px.
> Fixed font-size in Rovo Dev prompt box

- scripts/version/assert-nightly.sh
This change checks if the nightly version already exists before kicking off a build for it.
It's going to save ~ 15 minutes or more for nightly builds that, because of a bug, they end up choosing a version that already exists.
> Asserts that nightly version does not exist before building it

- scripts/version/get-next-nightly.sh
Tiny change to make the version resolution logic that happens on builds a bit more verbose, to debug the odd discrepancy between `release` and `release-nightly`
See picture above ;)
> chore: make nightly version resolution more verbose

- src/lib/ipc/toUI/config.ts
- src/lib/webview/controller/config/configV3WebviewController.ts
- src/lib/webview/controller/config/configWebviewController.ts
- src/react/atlascode/config/ConfigPage.tsx
- src/react/atlascode/config/ConfigPageV3.tsx
- src/react/atlascode/config/advancedConfigs/advancedConfigsPanel.tsx
- src/react/atlascode/config/configController.ts
- src/react/atlascode/config/general/GeneralPanel.tsx
The unique ID from vscode used in experimentation is now shown at the bottom of advanced settings
Old settings page:
New settings page:
See images above :)
Basic checks:
> [AXON-971] show machine id in advanced settings

- src/react/atlascode/config/ConfigPageV3.tsx
- src/react/atlascode/config/generalAuth/AuthPanel.tsx
- src/react/atlascode/config/generalAuth/AuthenticationPanel.tsx
- src/util/featureFlags/features.ts
Added a Product Toggle for the new config page. 
- Manual Testing
Basic checks:
> Added Product Toggle for new config page

- package.json
- src/commandContext.ts
- src/container.ts
- src/util/featureFlags/features.ts
The new authentication flow is now under a feature flag, `atlascode-use-new-auth-flow`
| No feature flag | Yes feature flag |
|----|---|
| <img width="787" height="379" alt="image" src="https://github.com/user-attachments/assets/0368b671-697e-43ed-ad2d-cb53902bbd73" /> | <img width="757" height="160" alt="image" src="https://github.com/user-attachments/assets/0e2a19a5-4233-4395-ae06-65fa960eb13c" /> |
A bunch of override attempts + see images above :)
Basic checks:
> [AXON-971] add feature flag for the new auth flow

- src/commands.ts
- src/constants.ts
- src/views/jira/treeViews/utils.ts
With the feature flag turned on, this button now triggers the new authentication flow
[Loom on this](https://www.loom.com/share/9fe101db919e4c6d85fcc3ad21ea6b95)
Manually, with FF both on and off
Basic checks:
> [AXON-972] Connect Jira auth flow to TreeNode login button

- src/container.ts
- src/lib/ipc/fromUI/config.ts
- src/lib/webview/controller/config/configV3WebviewController.test.ts
- src/lib/webview/controller/config/configV3WebviewController.ts
- src/lib/webview/controller/config/configWebviewController.test.ts
- src/lib/webview/controller/config/configWebviewController.ts
- src/react/atlascode/common/FeatureFlagContext.tsx
- src/react/atlascode/config/ConfigPage.tsx
- src/react/atlascode/config/ConfigPageV3.tsx
- src/react/atlascode/config/auth/SiteAuthenticator.tsx
- src/react/atlascode/config/configController.test.ts
- src/react/atlascode/config/configController.ts
- src/webview/singleViewFactory.ts
This change does 2 things:
1. Establish a way to propagate and use feature flags to our `SingleWebview`-architecture webviews via `FeatureFlagContextProvider`. At the moment, it's only used in `settings` pages
2. Use the new context provider to plug the new authentication flow into Jira panels in both versions of our settings page
The visual part:
| Old settings | New settings |
|----|----|
|<img width="400" alt="image" src="https://github.com/user-attachments/assets/dd3682ac-955f-4204-ab1b-fac9a343a32d" />|<img width="739" height="240" alt="image" src="https://github.com/user-attachments/assets/f2a35658-0666-40cc-8ae1-fa8d7768ec74" />|
|<img width="600" alt="image" src="https://github.com/user-attachments/assets/d51d8176-85d6-4577-a0ee-f3e9bf7d7abd" />| <img width="600" alt="image" …
> [AXON-973] Add featureflags to webview; new auth button

- .github/workflows/build.yaml
This change instructs GitHub to cancel an ongoing build action for the same PR when a new build has been triggered.
This is to avoid wasting resources on a build that becomes stale.
- It hasn't.
> Build action: Cancel previous build when new one is triggered

- src/onboarding/quickFlow/authentication/authFlowUI.ts
- src/onboarding/quickFlow/authentication/states/common.ts
- src/onboarding/quickFlow/authentication/states/terminal.ts
- src/onboarding/quickFlow/authentication/types.ts
- src/onboarding/quickFlow/baseUI.ts
- src/onboarding/quickFlow/quickFlow.ts
- src/onboarding/quickFlow/types.ts
This change has several things going on at once (terribly sorry about that, it kind of just happened 😦):
1. Add an explicit failure state in the flow
2. Make it possible to `await` on the flow execution
3. Add a special type of loading UI, use it when running OAuth from any source
4. Reword the phrasing in the authentication type picker to bring it a bit more in line with design (this needs further cleanup)
5. Add a bit more instrumentation about failure states, specifically
There's going to be a very quick follow-up to this, including:
1. More cleanup on wording/design
2. More loading states for confirming cloud/server credentials, and a similar rework for those terminal states
Manually :)
Basic checks:
> [AXON-977] make quickflow awaitable + actually wait for OAuth

- src/onboarding/quickFlow/authentication/authFlowUI.ts
- src/onboarding/quickFlow/authentication/types.ts
> Edit: the 2nd commit brings `Full Access` option to the top
> <img width="777" height="301" alt="image" src="https://github.com/user-attachments/assets/f005f0fd-a0ea-4d72-a4e4-3fb955efb164" />
Small changes to word choice in places, with the general idea being _DON'T MENTION OAUTH ANYWHERE_, lol :D
(except in the one description for "Cloud - Basic")
Basic checks:
> [AXON-976] re-word and cleanup

- src/onboarding/quickFlow/authentication/authFlowUI.ts
- src/onboarding/quickFlow/authentication/states/common.ts
- src/onboarding/quickFlow/authentication/states/server.ts
> Note: this change takes care of edge cases in #874 
To make validation work in all cases, we might want to consider always having the PAT/password input at the end.
This change:
* Reorders server authentication process to ask for context path/SSL stuff first
* Does a minor cosmetic change of putting the default option for contextPath (`no`) on top
Manually - clicked through the process of server authentication
Basic checks:
> [NOISSUE] chore: server authentication - make password/PAT last step

- package-lock.json
- package.json
- webpack.react.dev.js
- webpack.react.prod.js
This PR adds proper support for Compiled CSS-in-JS to handle Atlaskit component styles correctly in our webpack configuration.
- Added `@compiled/webpack-loader` with proper configuration for CSS-in-JS extraction
- Configured `CompiledExtractPlugin` with `sortShorthand: true` for optimal style processing
- Added specific CSS rules to handle `.compiled.css` files generated by Atlaskit components
- Updated babel configuration with necessary presets and plugins for Compiled
- Keep `ignoreOrder: true` in `MiniCssExtractPlugin` to handle CSS ordering warnings - [details](https://github.com/atlassian/atlascode/pull/830/files#r2305607088)
Atlaskit components use Compiled CSS-in-JS (since October 2024) which requires specific webpack configuration to:
- Properly extract and bundle CSS styles
- …
> AXON-965: Configure webpack to support Compiled CSS-in-JS

- CHANGELOG.md
- src/webviews/createIssueWebview.ts
- Fix issue when site select is empty after changing the issue type
Behaviour before fix: 
https://github.com/user-attachments/assets/9ecd20de-a575-4810-b2c7-cff3e2fde25c
Behaviour after fix: 
https://github.com/user-attachments/assets/247abe01-b320-4bed-b3ab-3203b4e837cb
Basic checks:
> AXON-993: fix empty site select issue in create issue page

- src/react/atlascode/rovo-dev/common/common.tsx
- src/react/atlascode/rovo-dev/messaging/ChatMessageItem.tsx
Replaced `retry-prompt` rendering with te error's context for better understanding of error.
manually
Basic checks:
> [AXON-891]: added error msg into retry prompt rendering

- src/container.ts
- src/siteManager.test.ts
- src/siteManager.ts
Rovo Dev uses Jira sites' authentication token for its enablement and token usage.
If Jira is fully disabled, its sites shouldn't be used, therefore Rovo Dev should be disabled.
This PR addresses that.
> [AXON-1029] Rovo Dev should be disabled if the whole Jira feature is disabled

- src/react/atlascode/rovo-dev/prompt-box/prompt-input/PromptInput.tsx
> [AXON-1031] Rovo Dev prompt box gets reset on "eyed context" change

- src/react/atlascode/rovo-dev/prompt-box/prompt-input/PromptInput.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
Regression caused by #894: 
- Incorrect color of the promptbox text area
- Text doesn't reset after submit
> Rovo Dev: fixed color and submit regression in Prompt Box

- e2e/scenarios/jira/updateIssueStatus.spec.ts
- src/jira/transitionIssue.test.ts
- src/jira/transitionIssue.ts
**Problem**
When users drag Jira issues between status columns (e.g., from `"Done"` to `"In Progress"`), the issues would disappear from the "Assigned Jira Work Items" sidebar instead of appearing, or vice versa. This was happening because the sidebar refresh was occurring too quickly before Jira's API indexes were updated.
**Solution**
Added a 4-second delay (`OnJiraEditedRefreshDelay`) before refreshing the sidebar views, consistent with other parts of the codebase that handle Jira issue updates.
**Demos**:
Before
https://www.loom.com/share/00c00bde760146679e59eb3b74304368
After
https://www.loom.com/share/467e735db92d410cbe3f09e2baab3bea
Basic checks:
> AXON-994: Add delay to Jira issue transitions for proper sidebar updates

- src/rovo-dev/performanceLogger.test.ts
- src/rovo-dev/performanceLogger.ts
- src/rovo-dev/rovoDevChatProvider.ts
- src/rovo-dev/rovoDevTelemetryProvider.ts
- src/rovo-dev/rovoDevTypes.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
The Rovo Dev webview provider grew too big to be properly maintainable.
This change extracts from it:
- the chat management, including replay and cancellations, into `RovoDevChatProvider`
- the telemetry code, into `RovoDevTelemetryProvider`
> Refactor Rovo Dev webview provider

- src/react/atlascode/rovo-dev/common/common.tsx
**Before**:
**After**:
https://www.loom.com/share/3ce69f63c7bf4799be30f42ed7cf0c0d
Basic checks:
> AXON-1056: RovoDev: URLs in the chat should be clickable

- src/react/atlascode/rovo-dev/rovoDevView.tsx
Cleaned up deep plan state on:
- finalizeResponse
- handleAppendError
- cancelResponse
Basic checks:
> AXON-1011 - reset Start Plan button on response finalization, error, and cancellation

- package.json
- src/commands.ts
- src/container.ts
- src/rovo-dev/rovoDevUtils.ts
Also, if the `mcp.json` or the .memory.md` file don't exist, it creates them.
The `config.yml` file is not being auto-created as
- it's supposed to be already there if Rovo Dev has been started
- its default state cannot be determined by Atlascode
> [AXON-803, AXON-1062] Expose Rovo Dev commands in the view's context menu

- src/analytics.ts
- src/rovo-dev/rovoDevDwellTracker.test.ts
- src/rovo-dev/rovoDevDwellTracker.ts
- src/rovo-dev/rovoDevTelemetryProvider.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
When Boysenberry mode is enabled, track when users dwell on AI Generated code, and send an `aiResult viewed` analytic event if the user dwells for 5+seconds.
Loom demo: https://www.loom.com/share/026d89ce9d5449a49105817f7d48b82d
- Unit tests
- Tested locally - see loom demo
Basic checks:
N/A - only applicable for Boysenberry mode
N/A - not user-facing change
> FLOW-486 Add aiResult analytic after viewing file for 5s

- src/rovo-dev/rovoDevFeedbackManager.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
Added the Rovo Dev Session ID to help with investigations if user's are reporting a problem, this will help us search in Splunk logs
Added this to my local .env - which is the environment variable platform saves our session id in
```
SANDBOX_SESSION_ID=bf6f3d33-6f37-46a1-97a3-8125d4217685
```
Ran editor locally, and submitted feedback
https://customerfeedback.atlassian.net/jira/servicedesk/projects/DAIF/queues/custom/3907/DAIF-2217
> Add the Rovo Dev Session Id to the feedback form

- src/react/atlascode/rovo-dev/RovoDev.css
- src/react/atlascode/rovo-dev/prompt-box/prompt-input/PromptInput.test.tsx
- src/react/atlascode/rovo-dev/prompt-box/prompt-input/PromptInput.tsx
- src/react/atlascode/rovo-dev/prompt-box/prompt-settings-popup/PromptSettingsPopup.tsx
- src/react/atlascode/rovo-dev/prompt-box/updated-files/UpdatedFilesComponent.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/technical-plan/CodePlanButton.test.tsx
- src/react/atlascode/rovo-dev/technical-plan/CodePlanButton.tsx
Change button + border radii + padding styles to match BBY styles
Changes:
manually
Basic checks:
> AXON-1143: change chat styles to match BBY designs

- src/commands/jira/createIssue.ts
- src/commands/jira/issueSuggestionManager.ts
If the API key is not provided for the AI issue suggestion:
* Don't try to make the API call 🤦 
* Use uniformly generated summary/description as fallback
Manually
Basic checks:
> [AXON-823] Minor fix to the work item suggestion

- src/react/atlascode/rovo-dev/common/common.tsx
- src/react/atlascode/rovo-dev/create-pr/PullRequestForm.tsx
- src/react/atlascode/rovo-dev/messaging/ChatMessageItem.tsx
- src/react/atlascode/rovo-dev/technical-plan/FileToChangeComponent.test.tsx
- src/react/atlascode/rovo-dev/technical-plan/FileToChangeComponent.tsx
- src/react/atlascode/rovo-dev/technical-plan/TechnicalPlanComponent.tsx
- src/react/atlascode/rovo-dev/tools/ToolReturnItem.tsx
Html tags should not be added to the DOM directly, but interpreted as text.
The markdown formatter has an option to disallow html to be included in the final formatting.
|-----|-----|
| <img width="298" height="76" alt="image" src="https://github.com/user-attachments/assets/202b29f2-9bb9-4a7a-b038-53eaf04f5417" /> | <img width="257" height="60" alt="image" src="https://github.com/user-attachments/assets/03dbb305-1997-4cb2-930f-41c1fce6fdec" /> |
> [AXON-1140] Fixed Rovo Dev prompts injecting html into the view

- src/ipc/issueActions.ts
- src/webviews/createIssueWebview.ts
Small change to follow the (somewhat cursed) type enforcement pattern in `createIssueWebview`. Basically, we no longer use `(x as any)` in places
Manually! But also, there's basically no meaninful changes to the logic here
Basic checks:
> [AXON-823] chore: consistently enforce typing in createIssueWebview

- src/rovo-dev/rovoDevApiClient.ts
- src/rovo-dev/rovoDevProcessManager.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
- src/util/waitFor.test.ts
- src/util/waitFor.ts
Fixed a bug in the healthcheck poll that was preventing the newly changed status to be detected.
Initialization time reduced thanks to this fix.
Also, added a try/catch in the inner fetch function of the api client to inform what's the failure reason when Node's fetch failed to send a request.
> [Rovo Dev] Fixed the healtcheck polling, and more informative API call failures

- src/rovo-dev/rovoDevProcessManager.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
- src/util/waitFor.test.ts
- src/util/waitFor.ts
When Rovo Dev can't initialize (unhealthy status), today we shut it down to dispose resources.
Unfortunately, when debugging, this is inconvenient because we can't access the terminal anymore to inspect its logs.
This change prevents the shutdown to happen when Rovo Dev fails to initialize.
> [Rovo Dev][Debuggability] Don't shutdown Rovo Dev when unhealthy so the terminal can stay alive

- eslint.config.mjs
- package-lock.json
- package.json
- src/react/atlascode/pullrequest/InlineRenderedTextEditor.tsx
- src/react/atlascode/pullrequest/NestedComment.tsx
- src/react/atlascode/rovo-dev/common/common.tsx
- src/webviews/components/RenderedContent.tsx
- src/webviews/components/issue/StartWorkPage.tsx
- src/webviews/components/selectFieldHelper.tsx
Added the following rule: https://eslint-react.xyz/docs/rules/dom-no-dangerously-set-innerhtml
to disallow the usage of React's dangerouslySetInnerHTML, since it's a security risk if not properly guarded.
Current usage has been allow-listed.
> ESLint: Disallow the use of React dangerouslySetInnerHTML

- src/analytics.ts
- src/analyticsTypes.ts
- src/commands/jira/issueSuggestionManager.ts
- src/lib/analyticsApi.ts
- src/vscAnalyticsApi.ts
Analytics event for issue suggestion feedback
Actual testing and iteration would need to happen once the event goes to amplitude
Basic checks:
> [AXON-826] Add issue suggestions feedback analytics event

- src/webviews/components/aiCreateIssue/AISuggestionHeader.tsx
- src/webviews/createIssueWebview.ts
Add API token authentication nudge to the create issue page, in line with how we do it in rovodev
|Before|After|
|------|------|
|<img width="590" height="133" alt="image" src="https://github.com/user-attachments/assets/34106930-a4c8-4a16-aad0-a8ffc3e4e055" />|<img width="595" height="139" alt="image" src="https://github.com/user-attachments/assets/411b8d45-076b-44ae-b95a-567b2a7b0cad" />|
Notably, this _doesn't_ refresh the page with the new credentials, that will be a separate PR
Manually! Also, more changes to come, turns out the logic where we check for token availability is a bit janky
Basic checks:
> Axon 1181 better auth nudge

- src/commands.ts
- src/onboarding/quickFlow/index.ts
Small PR tangentially related to the #1030 - for authentication, use direct call when possible if triggering quick flow commands
Ran into a type safety issue which was a bit unpleasant to debug because commands don't do argument type validation
Manually
Basic checks:
> [AXON-1811] chore: use direct call instead of command when possible

- src/rovo-dev/responseParser.ts
- src/rovo-dev/rovoDevApiClient.test.ts
- src/rovo-dev/rovoDevApiClient.ts
- src/rovo-dev/rovoDevChatProvider.ts
Consume the /v3 APIs instead of the /v2, which offer the ability to pause the streaming before every tool call to request user confirmation before executing them.
With this change, we automatically allow every tool call, which keeps the logic equivalent to the YOLO mode.
> [AXON-1215] Migrate to the Rovo Dev v3 APIs, still in YOLO mode

- src/webviews/components/issue/common/AtlaskitEditor/AtlaskitEditor.css
> AXON-1191: Fixed code block contrast issue on the high contrast

- src/webviews/abstractWebview.test.ts
- src/webviews/abstractWebview.ts
- src/webviews/createIssueWebview.ts
Whenever authentication or available site list changes, update the create issue page
This is particularly relevant to make the authentication nudge work as expected (you authenticate -> you get the new shiny feature right away :D)
Manually, see loom:
https://www.loom.com/share/036976c0a4254e28808903c899c888dc
Basic checks:
> [AXON-1181] Update suggestion availability on credential change

- src/analytics.test.ts
- src/analytics.ts
- src/react/atlascode/rovo-dev/create-pr/PullRequestForm.tsx
- src/react/atlascode/rovo-dev/rovoDevViewMessages.tsx
- src/rovo-dev/rovoDevTelemetryProvider.ts
- src/rovo-dev/rovoDevWebviewProvider.ts
Fire an analytic even when a user clicks the Rovodev "Create Pull Request" button.
https://www.loom.com/share/e47330bdbd4c42cebd5f2bf0f219205d?sid=ec4fe507-62d1-45dc-a8d3-6012f18696a2
- Tested locally and basic unit tests added
https://www.loom.com/share/e47330bdbd4c42cebd5f2bf0f219205d?sid=ec4fe507-62d1-45dc-a8d3-6012f18696a2
Basic checks:
> FLOW-344 Adds analytic event for rovodev create PR button clicked

- package-lock.json
There was something odd in the lockfile around `ovsx` dependencies (it was complaining about `crc32`)
The change here came about like this:
1. Remove `ovsx` from deps
2. Add it back
3. Commit the resulting lockfile :D
Disclaimer: there might still be unrelated flakiness in the actual `ovsx` push, which is still optional
Via branch [fix-ovsx-question-mark](https://github.com/atlassian/atlascode/tree/refs/heads/ovsx-fix-question-mark) and these two builds
| [before](https://github.com/atlassian/atlascode/actions/runs/18027459735/job/51297353138) | [after](https://github.com/atlassian/atlascode/actions/runs/18027558360/job/51297626328) |
|---|---|
| <img width="1150" height="467" alt="image" src="https://github.com/user-attachments/assets/161250d9-a7b0-4f52-a4cf-072babc9c3dc" /> | <img …
> [AXON-1248] chore: fix ovsx dependencies

- CHANGELOG.md
- src/atlclients/loginManager.test.ts
- src/atlclients/loginManager.ts
**Current behaviour:** 
**Fixed behaviour** ( leave just one connected via api token site at a time and show related info message):
https://www.loom.com/share/4b53712a1c2449eebf3a19f8b9a8be43
Basic checks:
> AXON-1099: leave just one connected via api token site at a time

- src/atlclients/issueBuilder.test.ts
- src/atlclients/issueBuilder.ts
- src/commands/jira/issueSuggestionManager.ts
- src/webviews/createIssueWebview.ts
This change rewrites how we resolve API token availability for the purpose of issue suggestions
|  | Before | After |
|--|------|-------|
| When deciding if suggestions are available | Check for API token credential on specific site | Check for an API token applicable to the selected site (via matching email) |
| When making the API call | Use first available cloud site with an API token | Use the exact site the user has selected in the `Create Issue` page |
Also featuring: fix to a very annoying bug where the generated values would reset when switching sites
Manually :)
https://www.loom.com/share/3302b30e620947eeb9d3d7a1d58254b8
Basic checks:
> AXON-1181 use any available key

- src/atlclients/authStore.test.ts
- src/atlclients/authStore.ts
- src/atlclients/issueBuilder.test.ts
- src/atlclients/issueBuilder.ts
- src/commands/jira/issueSuggestionManager.ts
No functional change, small follow-up from #1041:
* Move `findApiTokenForSite` into `credentialManager` per @bwieger-atlassian-com's suggestion
* Add some more unit tests (and move the existing tests accordingly)
N/A
Basic checks:
> chore: move API token lookup to credential manager + more tests

- src/webviews/components/aiCreateIssue/AISuggestionFooter.tsx
- src/webviews/components/aiCreateIssue/AISuggestionHeader.tsx
Small changes to the header and footer of the issue suggestion UI to bring them in line with design - at least as much as possible, without reworking the page as a whole
This is purely cosmetic - please see the image above :)
Basic checks:
> [AXON-825] bring issue suggestion UI (somewhat) in line with design

- src/react/atlascode/rovo-dev/common/common.tsx
- src/react/atlascode/rovo-dev/messaging/ChatMessageItem.tsx
- src/react/atlascode/rovo-dev/messaging/ChatStream.tsx
- src/react/atlascode/rovo-dev/prompt-box/promptContext/promptContextCollection.tsx
- src/react/atlascode/rovo-dev/prompt-box/promptContext/promptContextItem.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
**Ticket:**
https://softwareteams.atlassian.net/browse/AXON-1142
**What Is This Change?**
Added context to prompt is not an anchor link
**Demo:**
https://www.loom.com/share/25435474ff4e4ac7823a25367efa0f8f
Basic checks:
> AXON-1142: added context to prompt is not an anchor link

- src/rovo-dev/rovoDevWebviewProvider.ts
|---|---|
|<img width="547" height="128" alt="image" src="https://github.com/user-attachments/assets/350e1154-5f16-4d64-9733-55e4c2f93896" />|<img width="618" height="613" alt="image" src="https://github.com/user-attachments/assets/d0e9b38c-3c3f-4b12-b4b9-ff474eac1763" />
Turns out we were missing content root for images which is present in all other webviews :)
See images above :)
Basic checks:
> chore: fix broken loading image in rovodev tab

- src/react/atlascode/rovo-dev/prompt-box/updated-files/UpdatedFilesComponent.test.tsx
- src/react/atlascode/rovo-dev/prompt-box/updated-files/UpdatedFilesComponent.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
**Issues**:
AXON-1173:
Sometimes when Rovo dev responds with multiple modified file tool returns quickly, the updated files list does not include all modified files
AXON-1242:
Capitalisation on "1 Updated file" -> Can we please change to sentence case to align with Atlassian content standards? So this should be: "1 updated file"
**Recordings**:
Before:
https://www.loom.com/share/8a696b32fae849ad831762879e9942a6
After:
https://www.loom.com/share/811007e5339143d7af85fca6c17ee538
Basic checks:
> AXON-1173 - fixed race conditions in Updated files list

- src/react/atlascode/startwork/v3/components/UpdateStatusSection.test.tsx
- src/react/atlascode/startwork/v3/components/UpdateStatusSection.tsx
It seems that it was just a conflict between two `useEffects`.
|:--|:--|
| <img width="242" height="107" alt="image" src="https://github.com/user-attachments/assets/3995c99b-2121-400c-9db5-53f3d8c040f7" /> | https://www.loom.com/share/62d38eee2b3d402189f645337bd72885 |
Basic checks:
> AXON-1253: [Start Work Page] New state should default to "In progress"

- src/react/atlascode/rovo-dev/common/DialogMessage.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/tools/ToolCallItem.test.tsx
- src/react/atlascode/rovo-dev/tools/ToolCallItem.tsx
- src/react/atlascode/rovo-dev/utils.test.tsx
- src/react/atlascode/rovo-dev/utils.tsx
- src/rovo-dev/responseParser.test.ts
- src/rovo-dev/responseParser.ts
- src/rovo-dev/responseParserInterfaces.ts
- src/rovo-dev/rovoDevChatProvider.ts
- src/rovo-dev/rovoDevWebviewProviderMessages.ts
The new tool call interface includes the `mcp_server` field when the tool is invoked from an MCP server.
Rovo Dev also introduced a new tool call named `mcp_invoke_tool` which represent the invocation of a tool from an MCP server:
This change also fixes the issue:
[AXON-1277] Update Rovo Dev tool-call interface, and small refactoring
This change also refactors the parser interfaces into their own file, and creates the `RovoDevToolName` type enumerating all possible tool call names.
[AXON-1277]: https://softwareteams.atlassian.net/browse/AXON-1277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AXON-1277] Fix tool permission dialog not disappearing, and update Rovo Dev tool-call interface

- src/commands/jira/issueSuggestionManager.ts
- src/feedback/JSDSubmitter.ts
- src/ipc/issueActions.ts
- src/webviews/components/aiCreateIssue/AISuggestionFooter.tsx
- src/webviews/createIssueWebview.ts
* Implement a somewhat generic JSD sender for feeature feedback that works with a new queue
* Add feedback form to the create issue page, in line with Slack design
Coming in a follow-up:
* some rewords
* hiding the thumbs buttons after feedback is sent
* using an actual queue instead of a test one (only requires some ID chages)
See images above :)
Basic checks:
> [AXON-830] Add feedback collection from issue suggestions

- src/container.ts
- src/react/atlascode/rovo-dev/RovoDev.css
- src/react/atlascode/rovo-dev/common/DialogMessage.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/react/atlascode/rovo-dev/utils.tsx
- src/rovo-dev/responseParser.test.ts
- src/rovo-dev/responseParser.ts
- src/rovo-dev/responseParserInterfaces.ts
- src/rovo-dev/rovoDevChatProvider.ts
In case of parsing errors, we should not stop processing the returned stream.
Errors are going to be returned as a new type of messages, and handled appropriately.
Also, errors can now specify if they should be visible in debug mode only.
> [AXON-1292] Gracefully handle parsing errors, and hide certain errors from the user

- src/react/atlascode/rovo-dev/common/DialogMessage.tsx
- src/react/atlascode/rovo-dev/landing-page/disabled-messages/DisabledMessage.tsx
- src/rovo-dev/rovoDevChatProvider.ts
|-----|-----|
| <img width="359" height="219" alt="image" src="https://github.com/user-attachments/assets/52e0c9f1-1592-4d2b-a044-58ab8c8a8754" /> | <img width="372" height="221" alt="image" src="https://github.com/user-attachments/assets/582a8735-b1fa-433e-a668-34d8243fca1c" /> |
| <img width="375" height="204" alt="image" src="https://github.com/user-attachments/assets/3160d1af-4398-4117-b98c-d3822ad1ba2d" /> | <img width="375" height="178" alt="image" src="https://github.com/user-attachments/assets/a7f8874f-c8aa-4caa-9c04-565dc01ce984" /> |
> [AXON-1299, AXON-1300] Design alignment for Rovo Dev dialogs

- src/react/atlascode/rovo-dev/RovoDev.css
- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/rovo-dev/rovoDevWebviewProvider.ts
Some design tweaks for the rovodev chat section.
- Align "X updated files" header vertically with the filenames
- Increase padding on "keep" / "undo" buttons
- Make the "files drawer" section full width of the chat window
I also fixed a bug where the prHandler was not initialized somehow, and it caused an infinite loop of errors. No idea how to reproduce but I've added a sanity check to throw an error instead of looping hopefully.
Tested locally
Basic checks:
> AXON-1263 Design nits for the rovodev chat

- src/analytics.ts
- src/atlclients/authStore.ts
- src/atlclients/loginManager.ts
- src/lib/analyticsApi.ts
- src/siteManager.test.ts
- src/siteManager.ts
- src/vscAnalyticsApi.ts
Up until now, we've been overwriting API tokens when logging in with OAuth. Our new way of doing things suggests that API token credential is actually preferred, so this change changes the logic so that the API token is retained, instead
Changes:
* Exclude sites which are already using an API token from OAuth response
* Fix the logic where we merge all cloud sites after OAuth login to exclude sites with API tokens
* Add analytics
Manually - please see #axon for the demos
Basic checks:
> [AXON-1301] retain API token credentials through OAuth

- src/react/atlascode/rovo-dev/common/DialogMessage.tsx
- src/react/atlascode/rovo-dev/utils.tsx
- src/rovo-dev/rovoDevChatProvider.ts
Caused by #1086.
When non debugging, parsing errors were still rendered but hidden, causing the thinking block to split up.
Fix is to not render them at all.
> [AXON-1310] Fix broken thinking block when parsing errors occur

- src/react/atlascode/rovo-dev/rovoDevView.tsx
- src/rovo-dev/rovoDevWebviewProvider.ts
Fixed this issue, which happens if you have a prompt pending before denying an MCP server:
> [AXON-1313] Fix 'fetch error' right after denying an MCP server terms

- src/react/atlascode/startwork/v3/components/BranchPrefixSelector.test.tsx
- src/react/atlascode/startwork/v3/hooks/useStartWorkFormState.test.tsx
- src/react/atlascode/startwork/v3/hooks/useStartWorkFormState.ts
- src/react/atlascode/startwork/v3/utils/branchUtils.test.ts
I’ve fixed the field behavior: if a user has at least one custom prefix, they see the prefix field with a custom prefix selected by default (non-Bitbucket repo). If they have no custom prefixes and no branching model (as with non-Bitbucket repositories), the prefix field is hidden as unnecessary. In any case, the user can still type any prefix manually if they wish
| Before | After (with custom prefixes) | After (without custom prefixes) |
|:--|:--|:--|
| <img width="602" height="206" alt="image" src="https://github.com/user-attachments/assets/4819f2d9-9843-4a05-9e8f-428382381588" /> | <img width="353" height="279" alt="image" src="https://github.com/user-attachments/assets/756a0c1f-a010-4d1b-9403-b3fbddecc5ba" /> | <img width="355" height="212" alt="image" …
> AXON-1258: [Start Work page] Properly reset branch prefix

- src/container.ts
- src/views/HelpExplorer.ts
Question time! What do these have in common?
* Rovodev Help Section
* Weeping Angels from Dr. Who 
* SCP-173 
Answer - all of them only move if the user isn't looking :D
Up to now, there was a race condition in the behaviour of the rovodev button in our help section - it was only added if the help section got loaded before rovodev (e.g. if the user had the normal Atlassian tab open)
This forces the content to update every time 
Please refer to the videos on Axon channel
Basic checks:
> [AXON-1314] fix: updade help section w/ rovodev consistently

- jest.config.ts
- src/rovo-dev/rovoDevChatProvider.ts
Small fix to prevent the XML context from getting rendered as part of the message after being returned in `replay`
| Before | After | With context parsing |
|----|----|----|
| <img width="55" height="229" alt="image" src="https://github.com/user-attachments/assets/de99e0a0-ffa2-4de6-a02b-54c3d70b7606" /> | <img width="93" height="77" alt="image" src="https://github.com/user-attachments/assets/f2c48655-d1a4-4df2-ab89-ced126b7f4d5" /> | <img width="203" height="85" alt="image" src="https://github.com/user-attachments/assets/ceae6877-de84-446c-8983-f13fdfb811f2" />
This is intended as a stop gap, the underlying issue should be addressed separately
Manually in local env, see screenshots
Basic checks:
> Axon 1312 suppress context on replay

- CHANGELOG.md
- src/rovo-dev/rovoDevWebviewProvider.ts
Remove the "Boysenberry" word from user facing messages 
From: https://atlassian.slack.com/archives/C08HHS3DQTU/p1759840263147819 
Manual
> remove bby from error message strings

- src/react/atlascode/rovo-dev/landing-page/RovoDevLanding.tsx
- src/react/atlascode/rovo-dev/landing-page/RovoDevSuggestions.tsx
- src/react/atlascode/rovo-dev/messaging/ChatStream.tsx
- src/react/atlascode/rovo-dev/rovoDevView.tsx
Change actions to fill the prompt box instead of sending the context
**Current behavior ( sending the context ):** 
https://github.com/user-attachments/assets/0b01b073-6fce-4db3-b766-0ca48d61f71b
**Fix ( filling the prompt box ):**
https://github.com/user-attachments/assets/ea0ab6f6-a8b2-4692-bbda-ee74cc03ec6e
Basic checks:
> AXON-1282: actions should just fill the prompt
